### ISSUE TITLE
Update to 2.4 removed the UI

### ISSUE THREAD

**Issue by colekenny** [vitormhenrique/OctoPrint-Enclosure#11]
After updating to Version 2.4, the GUI on the web interface is no longer visible. See the attached picture.

![enclosurepluginui](https://cloud.githubusercontent.com/assets/17507643/24104821/cc3856ac-0d48-11e7-9a92-26b1e22cefef.png)

**Comment by vitormhenrique** [comment]
Go to the setting screen, and enable all the features that you want to use.

**Comment by colekenny** [comment]
Can't believe I didn't think to go there... Thanks, that fixed it. This issue can be closed.
