### ISSUE TITLE
Just updated; now blank Plugin tab....?

### ISSUE THREAD

**Issue by Petclaud** [vitormhenrique/OctoPrint-Enclosure#110]
You plugin is great! However, I have just updated both my Octoprint servers to the latest release and now on both servers, the Octprint TAB's are completely empty....? De-installing and re-installing does not fix this.

Any thoughts?

![knipsel](https://user-images.githubusercontent.com/28214663/37180708-4d33dc02-232a-11e8-98f3-20201eba378b.PNG)

P.S.
I am also running the TAB Order plugin maybe this has something to do with it..?

**Comment by vitormhenrique** [comment]
Well, you did not read the [release notes](https://github.com/vitormhenrique/OctoPrint-Enclosure/releases/tag/4.02) , it was **clearly** indicated that that would happen.
I spent more than 120 hours, of my free time, upgrading and coding this plugin with user requests, and people don't stop 2 minutes to read the documentation, it is frustrating...
