### ISSUE TITLE
Turn on and off USB Webcam

### ISSUE THREAD

**Issue by kodacy** [vitormhenrique/OctoPrint-Enclosure#111]
First! thank you for your wonderful job on OctoPrint-Enclosure plug-in Vitor.

One thin that would be great would be the capability of turning your USB webcam on and off by your plug-in.

On Octopi 0.13 it is quite simple with the SSH comands:
"sudo service webcamd stop" and "sudo service webcamd restart"

More info on: https://github.com/foosel/OctoPrint/issues/441

there is even ao cook book to do this on:
https://github.com/foosel/OctoPrint/wiki/Cookbook:-System-Commands

Any way to impertinent this commands directly in your plug-in?

**Comment by vitormhenrique** [comment]
Definitely possible, but I spent a lot of time on the last release, more than 120 hours, and I need to move on to other projects, I'll only focus on bugs for the next few months. So don't expect new release with new features for quite some time.

**Comment by kodacy** [comment]
Thank You! if i can help in any way just tell me.

**Comment by vitormhenrique** [comment]
Implemented ability to run shell scripts from outputs.
