### ISSUE TITLE
[Feature Request] Display temperature and toggles directly on the navbar

### ISSUE THREAD

**Issue by blazze11** [vitormhenrique/OctoPrint-Enclosure#114]
At the moment they are hidden behind a dropdown menu.
It would be nice to see them directly on the navbar.

**Comment by vitormhenrique** [comment]
With the new release it is possible to add way to much stuff on the navbar, including multiple temperature sensors, buttons to trigger outputs, etc. I did some testing and it would make the navbar way to crowded, having names and status and buttons.

I'm not going to revert this change, the navbar solution is clean and nice, you have access to all info and buttons without going to the enclosure tab, if you don't want to use the new features, just revert it back to the old plugin version, there you could have one temperature sensor, and it would show on the navbar.

Steps to do so:
- Clean all your configuration (very important)
- Uninstall the plugin
- Install if using the url option and this link https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/3.51.zip
