### ISSUE TITLE
Multiple Gpio per button

### ISSUE THREAD

**Issue by Drezzie** [vitormhenrique/OctoPrint-Enclosure#118]
I love this plugin, thank you very much. one thing i could wish for though is being able to tie more GPIOs together in one button. i have my lights on the gpio and it would be nice til be able to push only one button instead og 4 :) than you very much, hope you like the idea :)

**Comment by vitormhenrique** [comment]
I don't understand what you are saying, 
If you have 4 lights, each on one output, you need 4 buttons.
If you want to turn all lights at the same time, just use one output and tie all lights together in parallel.

**Comment by Drezzie** [comment]
I'm not strong on electrics, wouldn't that decrease the light from each
led?

**Comment by vitormhenrique** [comment]
If you are using led's directly from your raspberry pi to actually illuminate your printer you are doing it wrong.

Raspberry pi can only source / sink 16 mA per pin, and should not pass 51 mA overall current. That is NOT enough to use as light source. 

You should by a 5v led strip, and relay boards to control your lights. Follow the read-me, do some research.

And, answering your question, no parallel LED's WOULD NOT decrease the light (if you have power enough to run them to begin with) that is how your lights are wired on your house, if you remove one light bulb do the others become brighter? 

http://www.instructables.com/id/LEDs-for-Beginners/
