### ISSUE TITLE
Relay control not functioning properly

### ISSUE THREAD

**Issue by lurch68b** [vitormhenrique/OctoPrint-Enclosure#123]
[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/1885959/octoprint.log)
![capture01](https://user-images.githubusercontent.com/6299553/38450089-fcc208b6-39cc-11e8-9fab-aa6739fcd0e2.PNG)
![capture02](https://user-images.githubusercontent.com/6299553/38450090-fcda7860-39cc-11e8-8f88-2b87986dd2ed.PNG)

Ok, so I have been using your great plugin to control my setup for the last few weeks but I needed to make a new image to correct an error I made. Anyways I am controlling a relay board and every time I tried to make a new and I set up the relay control when I click the control for turning on/off relay 1 relay 2 activates and when I try to do the other relays they don't work at all. I did a test using the instructions you gave and everything works, well once I figured out that I needed to set the GPIO to board everything worked like a charm. I do notice that the updated version does not have the option to set for BCN or Board. Not sure if that was done in error. And not sure if the default setting is BCM now.

Thanks

**Comment by vitormhenrique** [comment]
I don't get it, you log is incomplete there is nothing there regarding the usage of the plugin, you need to delete the log, configure it, and use it for me to see.

The GPIO / BCM thing is still there, after you click on the "advanced section"

**Comment by vitormhenrique** [comment]
you are only showing print screens for the setup of one output, and you are telling me that you have two outputs setup, and when you click on number 1 number 2 is being activated, correct? 
Try to explain a little bit better what is going on...

**Comment by lurch68b** [comment]
Thanks, guys, I got it working. I didn't see the advanced options before. After fiddling with the GPIO settings and a GPIO reset and hard boot it is working now.

**Comment by vitormhenrique** [comment]
good!
