### ISSUE TITLE
Two DHT22 sensors do not display well

### ISSUE THREAD

**Issue by stusona** [vitormhenrique/OctoPrint-Enclosure#127]
I have one DHT22 sensor called "ambient, and one called "filament", and they do not display as expected.

![image](https://user-images.githubusercontent.com/17690666/38878864-d0bf544c-4216-11e8-9d7b-b3bcc77d11a7.png)

Great plugin! Thanks for all your work!

**Comment by stusona** [comment]
You betcha. I figured the logs were irrelevant, but I guess I should have just included them.

[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/1920501/octoprint.log)

![image](https://user-images.githubusercontent.com/17690666/38879932-5867afa0-4219-11e8-80ea-d366c1cbd9bc.png)

![image](https://user-images.githubusercontent.com/17690666/38879960-64bb5dec-4219-11e8-909f-1599e32092d4.png)

**Comment by vitormhenrique** [comment]
That is so weird,just as a test, if you delete both temperature sensors, and two dummy SI7021 sensors, what does it do?

**Comment by stusona** [comment]
I deleted both and created two SI7021 sensors without addresses:

![image](https://user-images.githubusercontent.com/17690666/38881098-2026c6b4-421c-11e8-86d3-907f49c2bf49.png)

**Comment by vitormhenrique** [comment]
Thanks, I'll try it out tonight, I tried to access my development raspberry pi from work but they blocked remote ssh connections...  
I'll update when I test it out...
Also noticed that you are using another skin for octoprint, can you tell me what is it? so I can see if it is related or not (probably not)

**Comment by stusona** [comment]
Thanks. I'd help but I don't know anything about javascript, css, etc. Maybe I should take an online course or something.

I'm using [Themeify](https://github.com/Birkbjo/OctoPrint-Themeify).

**Comment by vitormhenrique** [comment]
just fixed on master branch, just uninstall and install the plugin again, all settings should be ok...

**Comment by stusona** [comment]
Thanks Vitor!
