### ISSUE TITLE
Table for temperature sensors is not correctly formatted

### ISSUE THREAD

**Issue by dogbert1974** [vitormhenrique/OctoPrint-Enclosure#129]
Hi,

I've added 5 temperature sensors (DHT22) and found that the table formatting has some visibility error.
All the sensor are on the same line making the data unreadable:
![image](https://user-images.githubusercontent.com/38685951/39176169-70ed7184-47ac-11e8-8c09-0690daf192fb.png)
Maybe there are only some tags missing in the table.

p.s. should be nice to have a graph on the same page showing a graph of the data during time.

**Comment by vitormhenrique** [comment]
Hello, I just fixed this formatting issue few days ago, but I did not put a new release, so you  uninstall and install the plugin again, all your settings will remain.

For the temperature charing, that feature was already requested:

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/34

And I'm waiting the issue https://github.com/foosel/OctoPrint/issues/321 on octoprint itself be implemented so I can add temperature sensors to octoprint chart.

**Comment by dogbert1974** [comment]
Fantastic. Just checked online and found the update available. Now it works fine.

I really like this plugin.

Thank you very much.

**Comment by vitormhenrique** [comment]
No problem!
Thanks!
Just a heads up, having 5 dht sensors will probably make your pi work hard to get all the values.

I really encourage you getting other temperature sensors, if you only need temperature DS18B20 is chainable with one wire communication.

**Comment by dogbert1974** [comment]
I'm really going to use only three of them. 5 was to check the gpio settings. I will later add a power switch
