### ISSUE TITLE
Temperature control - Deadband

### ISSUE THREAD

**Issue by red-family** [vitormhenrique/OctoPrint-Enclosure#130]
Value Deadband doesn't work as expected. There is no hysteresis.

**Comment by vitormhenrique** [comment]
Can you explain what do you mean by that? What you expected from the dead band?
Current implementation is really just a simple dead band, for example, if your set point is 50 with 5 dead band on a heater setup, the temperature control should turn on the heater when the enclosure temperature reaches 45 and turn off when the temperature reaches 55. Between 50 + or - 5 the temperature will just keep the previous heater status.

**Comment by vitormhenrique** [comment]
I guess a better implementation would be implementing a regular temperature control [dead band](https://www.ia.omron.com/support/faq/answer/53/faq00549/).
And only have the dead band when turning "off" the temperature control, instead of on both sides.

**Comment by red-family** [comment]
My intention is to autostart the heater before printing to get faster the right temperature for printing.
Say 30 degrees. After the point is reached. Heater goes off and the heatbed of the printer is the only heat source.
For now the temp should regulated by fan at 35 degrees with 2 degress oh hysteresis. So it should start at 35 and stops at 33.

Hope this will help for explanation. 

----
mit freundlichen Grüßen 
Wolfgang RothAm 24.04.18, 19:20, Vitor de Miranda Henrique <notifications@github.com> schrieb:
The current implementation would have hysteresis on both sides of the set point...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vitormhenrique/OctoPrint-Enclosure","title":"vitormhenrique/OctoPrint-Enclosure","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vitormhenrique/OctoPrint-Enclosure"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vitormhenrique in #130: The current implementation would have hysteresis on both sides of the set point..."}],"action":{"name":"View Issue","url":"https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/130#issuecomment-384012583"}}}

**Comment by vitormhenrique** [comment]
I changed the implementation to follow a more regular hysteresis approach following this: https://www.ia.omron.com/support/faq/answer/53/faq00549/

Uninstall and intall the plugin again and give it a try...

Changes are listed here: https://github.com/vitormhenrique/OctoPrint-Enclosure/commit/208d4d800cf0e19cf03b2f06d56fc9fb3aadb68b

**Comment by vitormhenrique** [comment]
With this i think it will accomplish what you expect, but slightly change the heater.
If the temperature is set to 50, with 5 dead band, it will turn off the heater when the temperature reaches 50 and turn it on again when it turns 45. 
For the cooler it would do the opposite.

**Comment by red-family** [comment]
Is there a way to log the temperature from sensoŕ and the gpio outputs ?

**Comment by vitormhenrique** [comment]
Not really.
If you enable debug mode it will log temperature reading and status change on the main octoprint log, but it will be a pain to put that information together cleaning the other data.

**Comment by red-family** [comment]
And it would be great if the status of the temperature controls can be seen on the webpage like the normal gpio's.
I mean if they are on or off.

**Comment by red-family** [comment]
i enabled the debug mode and will have a try again, because it hasn't worked yet

**Comment by red-family** [comment]
ok, i tested this time only with fan as cooler at 30 degrees with 2 degrees deadband.
what happened ? 
fan started at 30 degrees and it goes on for 10 seconds, stops for 10 seconds, starts again for 10 seconds and so on.
This happened just the temperature reaches 28 degrees..
please find attached the octoprint logfile

kindly regards

[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/1948350/octoprint.log)

**Comment by vitormhenrique** [comment]
Finally fixed this issue and properly tested.

**Comment by red-family** [comment]
thx.
works perfect
