### ISSUE TITLE
"Use Board Pin #" checkbox not displayed correctly.

### ISSUE THREAD

**Issue by yschaeff** [vitormhenrique/OctoPrint-Enclosure#134]
While debugging an issue some time ago I noticed that the toggle "Use Board Pin #" in the advanced section is not displayed correctly. That is, I check the box, hit save and then revisit the config and the box is unchecked again. Though through observing  the behaviour it seems that the setting did indeed toggle.

**Comment by vitormhenrique** [comment]
fixed on the [new release](https://github.com/vitormhenrique/OctoPrint-Enclosure/releases/tag/4.09) update and test it out...
