### ISSUE TITLE
Input to control GCODE command?

### ISSUE THREAD

**Issue by areonic** [vitormhenrique/OctoPrint-Enclosure#135]
From what I can tell, as of now its not possible but wanted to ask anyway. Is there anyway to make it so when you push a physical button, it sends a gcode to the printer? I know as of now, you can do simple things that are preset in there to cancel, start, stop etc. But what about a box or something to input your own command line, is that possible?

**Comment by vitormhenrique** [comment]
Yes, it is possible, you need to configure one output as being a GCODE, and one INPUT to control that previous controlled output.
You can even control all inputs, outputs with enclosure specific custom gcodes...  
Check the documentation, the wiki page, or ask...
But take a look on the plugin settings, play with it, it is possible to do a lot of stuff....
