### ISSUE TITLE
Duty Cycle Error With PWM

### ISSUE THREAD

**Issue by mfocht001** [vitormhenrique/OctoPrint-Enclosure#144]
First, thanks for your efforts. This is a really cool plugin!

Now the issue:

I have created a Raspberry Pi Output in the Enclosure Plugin for an  **Output Type** of PWM button and I am getting a duty cycle error message when pressing button in UI. Also, for PWM Output type does not display or has no option to view in UI. 

I have tried the following:

1. Followed troubleshooting guide and removed all configured outputs (no inputs used).
2. Save blank configurations and rebooted RPI.
3. Save blank configurations and restarted Octo server.
4. Validated pins are correct. Setup an output using **Regular IO** and button works and lights up LED.
5. Checked config.yaml and the values are being saved under the plugin tree.

Hardware Raspberry Pi 3 PWM pin 18

Screenshots

![errorgit](https://user-images.githubusercontent.com/12564850/40865292-90bab8b4-65c5-11e8-8bb6-bcd5453c9bf0.png)

Last part of error log showing configuration update and button presses

`[{u'linked_temp_sensor': u'', u'startup_time': 0, u'temp_ctr_deadband': 0, u'neopixel_brightness': 255, u'new_duty_cycle': u'', u'gpio_pin': u'18', u'default_duty_cycle': u'50', u'neopixel_color': u'rgb(0,0,0)', u'hide_btn_ui': False, u'temp_ctr_set_value': 0, u'temp_ctr_default_value': 0, u'default_neopixel_color': u'', u'controlled_io_set_value': u'Low', u'auto_shutdown': False, u'label': u'Ouput 1', u'toggle_timer': False, u'toggle_timer_off': 0, u'alarm_set_temp': 0, u'auto_startup': False, u'controlled_io': 0, u'shutdown_time': 0, u'temp_ctr_type': u'heater', u'gcode': u'', u'temperature_b': 0, u'temperature_a': 0, u'neopixel_count': 0, u'duty_cycle': 0, u'toggle_timer_on': 0, u'show_on_navbar': False, u'duty_b': 0, u'duty_a': 0, u'pwm_status': 50, u'gpio_status': False, u'pwm_frequency': 50, u'startup_with_server': False, u'active_low': True, u'temp_ctr_max_temp': 0, u'pwm_temperature_linked': False, u'temp_ctr_new_set_value': u'', u'output_type': u'pwm', u'microcontroller_address': 0, u'index_id': 1, u'new_neopixel_color': u''}]
2018-06-01 22:09:36,161 - octoprint.plugins.enclosure - INFO - rpi_inputs: []
2018-06-01 22:09:36,163 - octoprint.plugins.enclosure - INFO - Setting GPIO mode to BCM
2018-06-01 22:09:36,165 - octoprint.plugins.enclosure - INFO - Setting GPIO pin 18 as PWM`

Full Log
[octoprint (1).log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2064322/octoprint.1.log)

**Comment by vitormhenrique** [comment]
Hello, what do you mean by "PWM Output type does not display or has no option to view in UI." ?
Your first print screen show the UI that it is supposed to show. What happens if you type a number, between 0 to 100 on the label that has the "off" grayed out and press the marker?

**Comment by mfocht001** [comment]
I mean that the PWM Output Type does not show like the IO Output Type.

Like this:
![ui-button-available](https://user-images.githubusercontent.com/12564850/40866294-f42a7ccc-65ca-11e8-8707-f3f0f6de1aa1.png)

When you create PWM Output Type it only does this:
![ui-nobutton](https://user-images.githubusercontent.com/12564850/40866315-0bc55d2a-65cb-11e8-9e3b-edd54620474f.png)
 
PWM Object Type does not show this option:
![uishow](https://user-images.githubusercontent.com/12564850/40866337-2760c40c-65cb-11e8-96ad-19f5ccd7575e.png)

If I try to add a value in the "off" field, it works but not unless I set it there. I am trying to simply add a button like the IO type and have three options show. One for low duty cycle/Medium/High.

**Comment by mfocht001** [comment]
Trying to do this but with PWM to dim lights:

![lowmediumhigh](https://user-images.githubusercontent.com/12564850/40866626-b05c140e-65cc-11e8-97e0-5fe98a83f874.png)

**Comment by vitormhenrique** [comment]
That is not suported. You can only control pwm using the ui section on the enclosure tab, you can also control it using custom g-code commands or link it to a temperature sensor.

**Comment by vitormhenrique** [comment]
Actually I figure it out a way that you can do it. 
Enagle g-code commands over the advanced section of the plugin, set up one PWM output. 
Than you set up three g-code outputs, and send different g-codes that will control your “pre sets pwm values”.
Look the wiki on how to set up g-cose outputs.

**Comment by mfocht001** [comment]
Thats only half of it. I am pointing out two things. One is what I was trying to do. which I get that it's not supported but there is still a problem that PWM Output type. It ignores the PWM values you enter and does not use the default_duty_cycle,

**Comment by vitormhenrique** [comment]
No no, you did not read the documentation and how it is supposed to work.
The default value is going to be written automatically if and only if you choose “automatically start up” for that output.
You can’t just press the button and expedt it to write it. If you choose to automatically start up that output, when a print starts it will automatically set that value for that output. Manually you can overwrite that value using the UI, set ir over the UI at any time or use the g-code commands.
If you just press the button on the output it will complain and expext you to tell it what value to write. This is by design.
If you want “pre set” values the only way is to use “g-code” outputs, you can creat as many as you want, link for that pwm output and it will create a button on the UI. When you press it it will “write” a PWM value that configure on the g-code.

**Comment by vitormhenrique** [comment]
The only way that it is supposed to work is by specifically writing the PWM value on the enclosure tab. And you already said that it was working doing this.
What I'm telling is that you can however accomplish what you want, that is creating buttons to set the pwm value to a specific value, even a "default" value.  I'll improve the documentation to avoid confusion, but this is only way that the plugin was designed.
