### ISSUE TITLE
Output for cooler is always active?

### ISSUE THREAD

**Issue by Jan2220** [vitormhenrique/OctoPrint-Enclosure#147]
Hello,
I was using this plugin to read the humidity in my drybox and monitor the room temerature for a while. Than i´ve added a DS18B20 Temp Sensor for the powersupply which was also working well. But now i have connected a fan to the raspberry pi to cool the powersupply when it is over a certain temperature. 
While the DS18B20 is still working i added a output and selected "Temperature / Humidity Control", put the GPIO Pin number in the box, selected the right sensor, selected cooler for the control type, and set the default temperature to 50. After that the Fan just starts to turn on even when the temperature is ~28°.
I just tried to put some other temperatures in the box but the Fan is still on.
To be sure i´ve tried to control the gpio manually with the following commands:
`gpio -g write 21 1`
`gpio -g write 21 0`
And the fan turns off and on. So i dont know why the plugin is now turning the fan/pin off when the temperature is below the 50° i´ve entered.

I hope you can help me

**Comment by vitormhenrique** [comment]
I need print-screens from your configuration and log...  but maybe you got the "active high" and "active low" swapped, try changing that setting...

**Comment by Jan2220** [comment]
what do you mean with priunt screens and where can i find logs?
otherwise i dont know where i can swap active high and active low. But the Fan is on even if the temperature is lower than the temperature i set.

**Comment by vitormhenrique** [comment]
On the setting screen, for that output, there is a check box to select between "active high" and "active low".
The default temperature it's NOT taken into account until you start a print. Just by saving the setting it will try to turn "off" the cooler.
I need to see your configuration, so you need to provide me with screen shots of your configuration, and attach them here... 

And for the logs: https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299

**Comment by Jan2220** [comment]
[octoprint (2).log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2094489/octoprint.2.log)
I now have tried again and noticed that it is possible to manually turn off/on the Fan though the Tab of the plugin. But i dont wont to set the temperature where it should stay everytime i print something. Now with the information that it will only try to cool if a print is running, i´ve tested again. I´ve tested with & without active low and changing the default temperatures. I started a print many times to try different configurations but no configuration was cooling the powersupply when the temperature is above the default and was doing nothing when the temperature is below the default. 
![chrome_2018-06-12_16-46-40](https://user-images.githubusercontent.com/20705433/41297808-42e0cf72-6e60-11e8-83c9-59a6b5037034.png)
![chrome_2018-06-12_16-47-02](https://user-images.githubusercontent.com/20705433/41297813-45bfe84a-6e60-11e8-9754-606231698af3.png)

**Comment by vitormhenrique** [comment]
You don't need to test "with or whiteout" the active low, you just need to follow whatever you have. Is your cooling on when you set the GPIO high or low? when you do the follow `gpio -g write 21 0` does it turn on or off?
Let's go on parts trouble shooting...

**Comment by Jan2220** [comment]
yeah, with the commands the fan/cooling will turn off or on

**Comment by vitormhenrique** [comment]
oh my.. please read CAREFULLY my comment, i'm asking if it turn ON the cooler or OFF?

**Comment by vitormhenrique** [comment]
also, if you don't check "Auto Startup" on the setting it will not set the default temperature. You need to mark **"Auto Startup"**

**Comment by vitormhenrique** [comment]
You just need to mark **Auto Startup** and figure it out if your sensor is active low or high

**Comment by vitormhenrique** [comment]
have you figure it out?

**Comment by vitormhenrique** [comment]
Closing this issue, @Jan2220 if you are still experiencing problems let me know.
