### ISSUE TITLE
Debounce time on inputs

### ISSUE THREAD

**Issue by maukcc** [vitormhenrique/OctoPrint-Enclosure#159]
Is it possible to add a debounce time on the inputs.
Like an input needs to be low(or high) for 250milliseconds to trigger.
This would be especially helpful for filament sensor, as you can then set it to 30000 milliseconds, allowing the printer to print up what is left of filament before going into pause mode.

**Comment by vitormhenrique** [comment]
Debounce is already implemented:
https://github.com/vitormhenrique/OctoPrint-Enclosure/blob/master/octoprint_enclosure/__init__.py#L945
Raspberry pi add_event_detect handles the debouce routine, and it is set to 200ms for any button.
For the filament detection I don't like the idea of "purging" the rest of the filament using debouce.  Filament detection should be placed as close as possible to the extruder / nozzle so you minimize loses, relying on delays could make you loose entire prints.
