### ISSUE TITLE
Temperature Control - I dont get it

### ISSUE THREAD

**Issue by echloton** [vitormhenrique/OctoPrint-Enclosure#160]
Hey there,
im having some trouble setting up the temp. control.
What i want: If the temp is above 30°C set GPIO 21 HIGH, if under 30 GPIO 21 LOW.

If i manually trigger GPIO 21 it works. I tried Values at Deadband (0-30/30/30-100) but none worked. Temp-Sensor is working and showing Temps (that make sense)

Im quite sure i get something wrong here and theres no bug.
![git1](https://user-images.githubusercontent.com/40473109/41739199-a3701376-7594-11e8-8f86-2fa4f81c11b3.PNG)
![git2](https://user-images.githubusercontent.com/40473109/41739200-a38d1098-7594-11e8-931e-77aeda93385c.PNG)
[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2124955/octoprint.log)

Best regards

**Comment by vitormhenrique** [comment]
dead band is just a integer, a value, not a range.
https://en.wikipedia.org/wiki/Deadband

you need to set deadband to zero to get what you want.

**Comment by echloton** [comment]
Ok, i have tried that. But Where do i Set the temp at which the pin goes high/low?

Cheers

**Comment by vitormhenrique** [comment]
on the enclosure tab, it's going to have a "set temperature" on the grid that displays the temperature.
you can also make it auto turn on and off and set a "default" value.

**Comment by echloton** [comment]
Ill try that, thanks!

**Comment by vitormhenrique** [comment]
Enclosure tab:
![2018-06-21 14_20_49-taz 5 octoprint](https://user-images.githubusercontent.com/3967383/41740735-89928d2a-755e-11e8-8395-e7b125cb83fe.png)

If you want to automatically start cooling with the print:
![2018-06-21 14_21_48-taz 5 octoprint](https://user-images.githubusercontent.com/3967383/41740734-89753068-755e-11e8-8c06-fa415c5ae7a7.png)

**Comment by echloton** [comment]
Thx alot, worked perfectly! Or works..better.
