### ISSUE TITLE
Compatible with psu control plugin 

### ISSUE THREAD

**Issue by Dutchy-79** [vitormhenrique/OctoPrint-Enclosure#163]
Hi,

Is this compatible with the PSU control plugin? 

I'd like to use a temperature sensor to switch off the power supply when it reaches a certain temperature. 

I'm not a programmer though I think it must be possible to cut power from gpio ## when gpio ## reaches +###© right?

**Comment by vitormhenrique** [comment]
This plugin completely replaces the PSU plugin,
You can use if with temperature sensor and a relay to control your PSU, or send GCode comands, or UI buttons etc...
