### ISSUE TITLE
Full temperature on nav bar

### ISSUE THREAD

**Issue by Dutchy-79** [vitormhenrique/OctoPrint-Enclosure#167]
Hi,

I've seen pictures with the full temperature on the van bar though all I see is a dropdown I have to click to see temperature.
Is there any way to write full temp to the nav bar?
![enclosure temp](https://user-images.githubusercontent.com/22749572/42523427-fddb8196-846d-11e8-9c78-165b866fc809.jpg)

best regards,

**Comment by vitormhenrique** [comment]
This was changed from previous to newer versions. On the past you could only get one temperature sensor, now you can add multiple, so staking them on the navbar is not an elegant solution, a compromise is having it under a sub-menu.
