### ISSUE TITLE
SI7021

### ISSUE THREAD

**Issue by jessefannon** [vitormhenrique/OctoPrint-Enclosure#177]
I am attempting to connect the SI7021 to octoprint.

I have enabled the I2C in the settings.  I have tested the sensor with the python file and it appears to be working correctly:
pi@octopi:~/oprint/lib/python2.7/site-packages/octoprint_enclosure $ python SI7021.py 40
25.5 | 56.3

My problem is that the Enclosure plugin page on OctoPrint is showing 0 for both the temp and humidity.  

Do you have any suggestions on what I may need to change to get them to display correctly?

![image](https://user-images.githubusercontent.com/42281731/43978658-0323f1b4-9cb6-11e8-9d30-cb9582aa0fd7.png)

**Comment by vitormhenrique** [comment]
1. enable / disable sudo under the advanced settings. 
2. follow the guideline and attach octoprint log when opening an issue.

**Comment by jessefannon** [comment]
My apologies for not following the guideline and attaching the log.  Disabling SUDO has fixed my problem.

Thank you.
