### ISSUE TITLE
Neopixel want work

### ISSUE THREAD

**Issue by Jacks3DPrinting** [vitormhenrique/OctoPrint-Enclosure#179]
Hi,

tryed to controll a neopixel ring via the plugin. But had no success.
If i use the examples from the jgarff´s library it works. 

Set the GPIO pin to 18 like in this tutorial.
https://learn.adafruit.com/neopixels-on-raspberry-pi/software

Iam using a 3B+

OctoPrint: 1.3.9
Enclosure Plugin: 4.12

(https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2300561/octoprint.1.log)

![unbenannt-2](https://user-images.githubusercontent.com/34211442/44311964-eee0f980-a3f0-11e8-98ba-4212a3254d27.jpg)

**Comment by vitormhenrique** [comment]
follow this:

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/172#issuecomment-410864599

**Comment by Jacks3DPrinting** [comment]
after reinstalling the python library and sudo visudo it works.

Big thanks awsome plugin :)
