### ISSUE TITLE
shutdown timouts

### ISSUE THREAD

**Issue by mcmasterp** [vitormhenrique/OctoPrint-Enclosure#18]
This may not be an issue in the next release already but I have two IO's set for fans. They are set to turn off 3 minutes after a print. the issue I'm seeing is that if the print ends and I start another before the shutdown delay has passed then they will still shutdown during that next print. since the IO start sequence has already fired at that point, they will remain off through whole operation.

I hope that's clear. ask any questions you need

**Comment by vitormhenrique** [comment]
Implemented on version 3.0 that is on dev branch right now, if you want to test it out uninstall the current plugin and install it again manually using the development branch. I still need to do more testing, all architecture of the software changed, so it might have few bugs.
 https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip
