### ISSUE TITLE
auto_shutdown

### ISSUE THREAD

**Issue by xXKarneXx** [vitormhenrique/OctoPrint-Enclosure#182]
After a few hours of printing, the plugin turns off the printer. But auto shut down is disabled.

2018-09-08 19:00:54,578 - octoprint.plugins.enclosure - INFO - Scheduling regular output id 2_auto_shutdown on 18845.423422 delay_seconds
2018-09-08 19:00:54,584 - octoprint.plugins.enclosure - INFO - Events scheduled to run [{'thread': <_Timer(Thread-646256, initial daemon)>, 'queue_id': '2_auto_shutdown'}]

[octoprint (8).log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2364042/octoprint.8.log)

**Comment by vitormhenrique** [comment]
picture of the settings please....
I would say remove the output that controls the printer, save the settings and create it again...
Something got messed up on your settings.

**Comment by vitormhenrique** [comment]
enable the debug under the advanced sections, delete the current output, save the settings, open the settings again, re-create the outputs and save it again, then send me the print-screens and new log file.

**Comment by vitormhenrique** [comment]
Any update?

**Comment by PPPBerlin** [comment]
In the UI, the setting is disabled, but it is still in the config.yaml. I spend lots of time to solve the problem, that my printer is shutting down every night at 00:20 and start to blaim my power supplier ;) So, please fix this setting and remove the shutdown_time correctly!

**Comment by vitormhenrique** [comment]
I can't reproduce your issue @PPPBerlin, if you don't add attach your configuration files, print screen of your configuration there is no way that I can help you.
