### ISSUE TITLE
Relais not switching off after print finished

### ISSUE THREAD

**Issue by Christian72D** [vitormhenrique/OctoPrint-Enclosure#184]
I have your described relais board attached to my Pi, i can switch the power of my printer on and off with the gui, but i´m not able th set it up to have i shut down the printer 10 minutes after print job finished.

Right now i have the PSU plugin installed again to auto shutdown the printer.

[enc1](https://user-images.githubusercontent.com/43115580/45266911-21679a80-b463-11e8-85aa-392ee03d3902.PNG)

**Comment by vitormhenrique** [comment]
You have incorrect settings, time toggle is to "blink" or turn on and off the GPIO after you start the print...
Read the documentation..
Disable time toggle, enable "auto shutdown" and configure your delay as you want it.
