### ISSUE TITLE
Enclosure plugin tab contains nothing

### ISSUE THREAD

**Issue by TTN-** [vitormhenrique/OctoPrint-Enclosure#185]
1. I installed the Enclosure plugin.

2. Restarted octoprint.

3. Went to octoprint tab and noted there was nothing there, see screenshot:

![image](https://user-images.githubusercontent.com/6019316/45416411-02237400-b6d4-11e8-9a90-2a45a70b7aac.png)

4. I checked the install log. Looks fine.

Attached: 
[plugin_pluginmanager_console.log.txt](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2374497/plugin_pluginmanager_console.log.txt)

This is octoprint version 1.3.9 this is a rather old install. Probably around 2 years old that has just been updated when updates are available.

If any other info is required please let me know.

**Comment by vitormhenrique** [comment]
I don’t understand, have you actually went to settings,  enclosure plugin
and set it up first? It is going to be blank by default.

You have to set it up first.

**Comment by TTN-** [comment]
OHHH.

What a face palm moment. It'd be helpful if its empty, it could contain a message saying go to settings, setup the plugin.

**Comment by sajovicd** [comment]
Or..... You could read some documentation...

**Comment by TTN-** [comment]
I did. I read the readme. Where does it have this information? I read the troubleshooting guide too and searched in closed issues and looked in open issues to find a solution. The answer was not easy to find. In fact I didn't find one at all and that's why I'm posting here. .. just tradin saying.. I tried..

**Comment by vitormhenrique** [comment]
@TTN- you clearly missed the Configuration part of the read-me. But that is ok...
