### ISSUE TITLE
neopixel - no module named neopixel

### ISSUE THREAD

**Issue by RyDanClemens** [vitormhenrique/OctoPrint-Enclosure#187]
I couldn't get my ws2812b strip to run through the enclosure plugin. They work just fine when testing it out through the ws281x library alone. I made all the changes you mentioned in [172](https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/172#issuecomment-410864599) and no luck. I think went tried the test script you wrote in [143](https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/143#issuecomment-394188491) and it kicked back: 

ImportError: No module named neopixel 

A little google-foo turns up that the neopixel module has been deprecated and is now being called rpi_ws281x.  [Ws281x Issue 290](https://github.com/jgarff/rpi_ws281x/issues/290#issuecomment-416623006)

I installed pip, then ran sudo pip install rpi_ws281x

then used nano to update the test script to reference rpi_ws281x instead of neopixel in the first line
ran the script, all was happy with the script. 

But I still cant get the actual enclosure plugin to do anything with the strip... I thought I updated the direct neopixel.py too but not seeing anything so far. suggestions?

**Comment by vitormhenrique** [comment]
I'll check this out when I have time, I changed jobs recently and it's being crazy, and I'm also going out on vacations for 30 days so it will be very difficult to check this this year....
