### ISSUE TITLE
IFTTT event receiving

### ISSUE THREAD

**Issue by WarrenSchultz** [vitormhenrique/OctoPrint-Enclosure#188]
**Is your feature request related to a problem? Please describe.**
Temperature / humidity triggers from IFTTT for additional data outside of RPi sensors.

**Describe the solution you'd like**
I've got temp/humidity sensors which work with IFTTT, I'd like to be able to poll that data, i.e. receive events from IFTTT triggers to initiate behavior on OctoPrint-Enclosure

See here for the specific model I'm using:
https://www.ambientweather.com/amws0265.html

**Comment by WarrenSchultz** [comment]
See here for the specific model I'm using:
https://www.ambientweather.com/amws0265.html

**Comment by vitormhenrique** [comment]
I don't plan to incorporate IFTTT, but I it is on the pipeline to implement MQTT, so it would kind of be possible to link the two together. You would need something to bridge the two, like home assistant, but it would be possible
Check this issue to get status when implemented: https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/40
