### ISSUE TITLE
Default temperature for enclosure

### ISSUE THREAD

**Issue by trgtylcnky** [vitormhenrique/OctoPrint-Enclosure#19]
Hi,
It would be nice to have a default temperature value in settings. It starts heating automatically when ~~octoprint~~ printing starts.

**Comment by sajovicd** [comment]
I dont think that would be a good idea To start heating when you turn on octopi. Or you mean whe you start printing?

**Comment by vitormhenrique** [comment]
I think the meant when started printing.

**Comment by trgtylcnky** [comment]
Yes, you are right.  I updated

**Comment by vitormhenrique** [comment]
Implemented on version 3.0 that is on dev branch right now, if you want to test it out uninstall the current plugin and install it again manually using the development branch. I still need to do more testing, all architecture of the software changed, so it might have few bugs.
 https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

**Comment by vitormhenrique** [comment]
Default temperature is not implemented, enclosure temperature control will start automatically  when the print starts.
