### ISSUE TITLE
Max temp request

### ISSUE THREAD

**Issue by TTN-** [vitormhenrique/OctoPrint-Enclosure#192]
Problem: I put a typo and add an extra digit when setting temperature, my machine melts.

Solution: Put a max temp parameter in somewhere.

Other comments: This hasn't happened to me (yet)

**Comment by vitormhenrique** [comment]
if you put 50000 on your enclosure set temperature, it will never get there realistically, unless you have a CRAZY heater installed. 
Either way there is already a maximum temperature field on the temperature / humidity control.
<img width="712" alt="screen shot 2018-11-07 at 10 55 20 pm" src="https://user-images.githubusercontent.com/3967383/48178750-f70a5000-e2e0-11e8-9b08-9552d23cc942.png">
