### ISSUE TITLE
Set by default an enclosure température

### ISSUE THREAD

**Issue by Lepterois** [vitormhenrique/OctoPrint-Enclosure#194]
Hi!
It would be great or I don't know to do it, to be able to fix by default a value for the temperature control of the enclosure.
Each time, I need to open the Enclosure plugin tab, and set a temperature value. After a reboot or A print stop, I need to do it again.
I don't find in the configuration tab a field where to set by default the temperature.
Or Is it possible to do it in the yaml?
Thanks in advance

**Comment by vitormhenrique** [comment]
If you enable auto-startup on the settings for the temperature control, on the very bottom of that output it's going to appear a "default value" field.
<img width="712" alt="screen shot 2018-11-07 at 10 55 20 pm" src="https://user-images.githubusercontent.com/3967383/48178632-59168580-e2e0-11e8-9929-20ba414beb1a.png">

**Comment by Lepterois** [comment]
Hi!
Yes I've done that but each time I switch off the printer, this value become empty.
Thanks
