### ISSUE TITLE
Request: output status

### ISSUE THREAD

**Issue by rtheil** [vitormhenrique/OctoPrint-Enclosure#20]
Would love to be able to see the current status of an output. Right now you can't tell if an output is on or off.

Absolutely love this plugin, so thanks.  Looking forward to next version. Sounds like some great additions!

**Comment by vitormhenrique** [comment]
Implemented on version 3.0 that is on dev branch right now, if you want to test it out uninstall the current plugin and install it again manually using the development branch. I still need to do more testing, all architecture of the software changed, so it might have few bugs.
 https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip
