### ISSUE TITLE
Setting BME280 sensor doesn't work

### ISSUE THREAD

**Issue by hozakjiri** [vitormhenrique/OctoPrint-Enclosure#202]
Hello guys, 

Please, can you help me? I have octoprint 1.3.10rc4 on Octopi 0.15.1. My problem is that the sensor BME280 doesn't work, but via putty it works. The library is correct but in octoprint are temperature and humidity zero.  In enclosure plugin i have address 0x76, if i write to command i2cdetect -y 1 i see my sensor on address 76. I don't know why it doesn't work.  If I write command sudo python BME280,py 76 to putty, he show temperature and humidity...23,2 celsius and humidity 58.

Thanks

**Comment by sebastian-heiden** [comment]
I have the same problem with th DHT22

**Comment by sebastian-heiden** [comment]
Hey I just found the solution to my proble.m
I had to disable the "use sudo" option in the "Advanced Options" tab. This might work also for your problem.

**Comment by vitormhenrique** [comment]
of course it does, it's on the troubleshooting guide... and plenty other open issues already opened here.
