### ISSUE TITLE
Preset buttons for PWM

### ISSUE THREAD

**Issue by sciaio** [vitormhenrique/OctoPrint-Enclosure#203]
Hi
Why not implementing some preset buttons for PWM output? Like 0% (or off), 25%, 50%, 75%, 100%. Sometimes it would be easier to set a value instead of manually insert it by keyboard.

Thanks, really appreciate it.

**Comment by vitormhenrique** [comment]
You can already accomplish this...

You can set up buttons to send g-code commands, and custom g-code commands can be used to set PWM information for any output.

https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/G-CODE-Control
