### ISSUE TITLE
Unable to set target temperatur 

### ISSUE THREAD

**Issue by b3ster** [vitormhenrique/OctoPrint-Enclosure#215]
First of all, great product I really enjoy your work.
Im using a self build case with a cooler and heater build in, controlled via gpio‘s from pi and temp sensors. My problem is that I’m unable to define the target temrature anymore, after upgrading I can’t find this option anymore. 
Hope you have some advice for me ?

The values marked on the screenshot can be changes at runtiome but no option to changes this persistent

![111e2965-8a60-4892-abf2-31c0471498ba](https://user-images.githubusercontent.com/28812766/52620761-bdc81a00-2ea5-11e9-8bfa-0db9c8d4c4f6.jpeg)

**Comment by sajovicd** [comment]
You can set temperature on setup page.

**Comment by vitormhenrique** [comment]
as @sajovicd said, if you have autostartup enabled on the settings you will be able to set a "default" temperature for the heater/ cooler.
