### ISSUE TITLE
Not getting temp reading from DHT22

### ISSUE THREAD

**Issue by Andreiva13** [vitormhenrique/OctoPrint-Enclosure#216]
**Describe the bug**
The sensor temp is always reported as 0 no matter what i do.
I did everything to install the appropriate library but still not working.
The test command from the install page works like a charm but not inside the octoprint GUI
[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2870754/octoprint.log)

**Comment by vitormhenrique** [comment]
Have you tried disabling sudo on the advanced section?

**Comment by Andreiva13** [comment]
That fixed it thank you!

**Comment by vitormhenrique** [comment]
You did everything BUT look the log, searching for this “issue”, and
looking the troubleshooting guide....

But glad you got it working...
