### ISSUE TITLE
Help: Shell Script to Power USB's On or Off - Details and Shell Scripts Inside

### ISSUE THREAD

**Issue by trbolexis** [vitormhenrique/OctoPrint-Enclosure#217]
I'm trying to run a shell script from a button to shut off USB's and another to turn them back on.

Currently, after powering my printer down, the screen/electronics stay 'on' because they are being powered by the Pi. I've been able to turn the USB ports on and off with the following commands in SSH.

- Turn USB Off: `echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/unbind`
- Turn USB On: `echo '1-1' |sudo tee /sys/bus/usb/drivers/usb/bind`

I've turned these into two separate commands: `powerUSBon.sh` and `powerUSBoff.sh` placed in `/home/pi/scripts/`

In SSH, if I send `/home/pi/scripts/powerUSBon.sh` or `/home/pi/scripts/powerUSBoff.sh` the action work correctly. The USB ports turn on/off corresponding to the command.

powerUSBon.sh:
![image](https://user-images.githubusercontent.com/36283021/52895751-74145380-3173-11e9-98bd-f8ce249b04ad.png)

powerUSBoff.sh:
![image](https://user-images.githubusercontent.com/36283021/52895744-5fd05680-3173-11e9-81f5-80291c83e46f.png)

After failing miserably to get this to work, I setup python scripts that call the shell script: 
on.py and off.py ::: These have both been placed in `/home/pi/scripts/`

::::::::::::::::::::::::::::

on.py
```
import os
os.system("/home/pi/scripts/powerUSBon.sh")
```
![image](https://user-images.githubusercontent.com/36283021/52895758-90b08b80-3173-11e9-9864-8c2293a75bca.png)

off.py
```
import os
os.system("/home/pi/scripts/powerUSBon.sh")
```
![image](https://user-images.githubusercontent.com/36283021/52895739-48916900-3173-11e9-8459-7c8d095dadcc.png)

Calling `python /home/pi/scripts/on.py` or `off.py` via SSH works to activate the script(s) and turn the USB on or off (respectively).

I'm at a loss, and I'm certain I'm overlooking something so I can't seem to get it to work. I have no prior experience with Linux, or Python, or Shell Scripting --- this is all trial and error after a LOT of reading online today.

Videos:
Using `python /home/pi/scripts/on.py` or `off.py`: https://www.dropbox.com/s/2myz6nuh8s7689i/20190215_225720_1.mp4?dl=0

Using `/home/pi/scripts/powerUSBon.sh` or `powerUSBoff.sh`: https://www.dropbox.com/s/6c0b9mucjbt7zif/20190215_230020_1.mp4?dl=0

Octoprint.log attached: 
[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2871698/octoprint.log)

Please advise.

**Comment by sajovicd** [comment]
Did you check sudo in advance setting?

**Comment by trbolexis** [comment]
Yes.

![image](https://user-images.githubusercontent.com/36283021/52896628-87c5b700-317f-11e9-89a1-e5760956c508.png)

**Comment by trbolexis** [comment]
I was able to get this to work by using the `python /home/pi/scripts/on.py` or `python /home/pi/scripts/off.py' within Enclosure plugin.

The last thing that I did was `chmod 777` permissions for `/sys/bus/usb/drivers/usb/bind' and `/sys/bus/usb/drivers/usb/unbind'

![image](https://user-images.githubusercontent.com/36283021/52905466-51c01b80-31ef-11e9-9d05-fd853d1af1f0.png)

Without setting permissions I kept getting 'permission denied' errors from the enclosure plugin.

::::::::::::::

I can also get it to work now after changing permissions for `powerUSBon` and `powerUSBoff`, respectively by entering '/home/pi/scripts/powerUSBon.sh` or '/home/pi/scripts/powerUSBoff.sh` within Enclosure Plugin settings. 

Lastly, I modified my two scripts to mask the "1-1" echo output:
![image](https://user-images.githubusercontent.com/36283021/52905504-ec205f00-31ef-11e9-89f1-6973859702a5.png)

![image](https://user-images.githubusercontent.com/36283021/52905508-fb9fa800-31ef-11e9-9ebc-881e6ef4c118.png)

Now Enclosure Plugin displays a nice confirmation message about the status:
![image](https://user-images.githubusercontent.com/36283021/52905513-107c3b80-31f0-11e9-9d61-9b01ad0325ff.png)

![image](https://user-images.githubusercontent.com/36283021/52905515-1d992a80-31f0-11e9-9a11-4694704d65a8.png)

![image](https://user-images.githubusercontent.com/36283021/52905514-170ab300-31f0-11e9-8bd2-693aedf00fd9.png)

I think the key was permissions settings... perhaps there is a more appropriate/elegant way to do this. 

Please let me know.

**Comment by trbolexis** [comment]
Next up: I need to figure out a way to make 1 button turn on/off USB and turn on/off GPIO in at the same time to make printer shutdown a 1 touch process.

Perhaps this can be done with additional python scripting or Enclosure GCODE? ...

**Comment by vitormhenrique** [comment]
Hello @trbolexis glad that you got it working, yeah, it was definitely permission! there is no other way around! I need to better document this on the wiki or read-me.
Yes, the best way to do multiple stuff on one button event is definitely using enclosure GCODES. 
You should still see the return message even by running the shell script via gcodes!

**Comment by sfgabe** [comment]
> Next up: I need to figure out a way to make 1 button turn on/off USB and turn on/off GPIO in at the same time to make printer shutdown a 1 touch process.
> 
> Perhaps this can be done with additional python scripting or Enclosure GCODE? ...

In case anyone is looking for this, I have a sample "Toggle" power switch on GitHub here: https://github.com/sfgabe/custom_scripts/blob/master/octoprint_relay_toggle.sh

I'm using a ramps board with 2 power sources, so I wanted a one touch on/off. For some reason I had to set it as a service to work correctly, but follow the info in the file and it should work.
