### ISSUE TITLE
Add input as API option

### ISSUE THREAD

**Issue by sfgabe** [vitormhenrique/OctoPrint-Enclosure#219]
As far as I can tell, currently only outputs are available via the API.

I'd like to be able to keep track of the ambient temp in the printer area with an attached temp sensor. For instance, if I want to print something when I get home, I can check the ambient temp ahead of time and turn up the heat in the garage via Nest etc. before I even get there.

I could just add in a background script that pushes the temp data to MQTT or IFTTT, but it seems like a good feature to have built in since it's _almost_ already there.

**Comment by vitormhenrique** [comment]
Hi @sfgabe, in theory the same API that the input has the output has as well.  But you would, either way, have to write something to pool the data from the plugin, the plugin has no way of publishing it yet. It will once I implement MQTT but for now it does not.
I have my octoprint open on the network, so i can access it remotely, but I have a secure installation. 
This other plugin implemented a layer of compatibility with mine:
https://plugins.octoprint.org/plugins/telegram/
So you can get all the data on your cellphone... 
I'm going to close this issue as when I implement a way to publish data from the plugin it will be on MQTT and we already have an issue open for that one.
