### ISSUE TITLE
can't toggle without connection

### ISSUE THREAD

**Issue by mcmasterp** [vitormhenrique/OctoPrint-Enclosure#22]
When the printer is disconnected the buttons grey out and can't be clicked. being able to use the gpios at all times would be great if possible

**Comment by vitormhenrique** [comment]
I added this to be consistent with the other buttons on the octoprint, I can definitely change that back.

**Comment by mcmasterp** [comment]
For my uses it would work best and I can't think how it harms anyone so I say go for it

**Comment by vitormhenrique** [comment]
Changed back to allow enclosure control when not connected to the printer.
