### ISSUE TITLE
Impulse

### ISSUE THREAD

**Issue by ghost** [vitormhenrique/OctoPrint-Enclosure#221]
You should add a pulse function for the On / Off buttons

on my 3D printer Ender3, I have a relay card that controls the 220V power supply

one of the relays controls an electrical outlet but it is not a socket connected to the internet, it works with a remote control of 433 MHz, so I connected the buttons of the remote control to my relays and the remote control requires a pulse of 1 second to switch on and off the relay corresponding to the socket.

Example:
Gpio On
Delay 1second
Gpio Off

**Comment by vitormhenrique** [comment]
same of https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/246
