### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by valepe** [vitormhenrique/OctoPrint-Enclosure#225]
Hi,
I use your plugin and very happy with it.
This morning I looked in the octoprint log because it went unresponsive to web calls and I saw a lot of errors from Enclosure plugin.
Every 10 seconds it fires these two lines:

2019-03-13 00:02:57,755 - octoprint.plugins.enclosure - WARNING - An exception of type IndexError occurred on log_error. Arguments:
('list index out of range',)
2019-03-13 00:02:57,756 - octoprint.plugins.enclosure - WARNING - An exception of type TypeError occurred on log_error. Arguments:
("'NoneType' object is not iterable",)

I don't know where to look to resolve the error.
Enclosure plugin:
 - drives a tworelay module (they works)
 - reads from MQ2 smoke sensor (never tryed)
 - reads from DS18B20 sensor (temperature values are fine)
 - reads two push buttons (they works)
 - reads a switch as filament runout sensor (until now never tryed)
and sends notifications via IFTTT (they work).

Can you help me where I can look in?

Thanks

**Comment by vitormhenrique** [comment]
Can you attach the entire log? And printscreen of you configuration?

**Comment by valepe** [comment]
here the full log file. When I'll come back home I'll send the screeshots. thanks
[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/2961436/octoprint.log)

**Comment by vitormhenrique** [comment]
From what i’m looking what I would try first is to delete all your settings
inside the plugin, save, and create them again.

Check the log after saving a blank settings to see if the error disappear.

**Comment by valepe** [comment]
Ok, I'll try that. In the meantime I made the screenshots.
<img width="721" alt="pic_01" src="https://user-images.githubusercontent.com/47390680/54316761-d3824980-45e1-11e9-9297-bad073f0a6b8.png">
<img width="721" alt="pic_02" src="https://user-images.githubusercontent.com/47390680/54316778-d54c0d00-45e1-11e9-960a-58811239d50f.png">
<img width="721" alt="pic_03" src="https://user-images.githubusercontent.com/47390680/54316779-d54c0d00-45e1-11e9-9578-54dc10db6a33.png">
<img width="721" alt="pic_04" src="https://user-images.githubusercontent.com/47390680/54316765-d41ae000-45e1-11e9-9b1b-e81ec0d78028.png">
<img width="721" alt="pic_05" src="https://user-images.githubusercontent.com/47390680/54316766-d41ae000-45e1-11e9-8d47-4804b513b6fb.png">
<img width="721" alt="pic_06" src="https://user-images.githubusercontent.com/47390680/54316769-d4b37680-45e1-11e9-9651-25c7a97cf74e.png">
<img width="721" alt="pic_07" src="https://user-images.githubusercontent.com/47390680/54316770-d4b37680-45e1-11e9-912e-2ab18d57984d.png">
<img width="721" alt="pic_08" src="https://user-images.githubusercontent.com/47390680/54316776-d54c0d00-45e1-11e9-9266-275ad37b1845.png">
<img width="721" alt="pic_09" src="https://user-images.githubusercontent.com/47390680/54316774-d54c0d00-45e1-11e9-8ecb-277d285ca2e1.png">
<img width="721" alt="pic_10" src="https://user-images.githubusercontent.com/47390680/54316764-d41ae000-45e1-11e9-9f4d-65971b4fda72.png">
<img width="721" alt="pic_11" src="https://user-images.githubusercontent.com/47390680/54316767-d41ae000-45e1-11e9-8eae-80bc8bf45104.png">
<img width="721" alt="pic_12" src="https://user-images.githubusercontent.com/47390680/54316768-d41ae000-45e1-11e9-993a-efaa463878d2.png">
<img width="721" alt="pic_13" src="https://user-images.githubusercontent.com/47390680/54316771-d4b37680-45e1-11e9-9974-a4d0c62c78b4.png">
<img width="721" alt="pic_14" src="https://user-images.githubusercontent.com/47390680/54316772-d4b37680-45e1-11e9-9f73-bd697608398f.png">
<img width="721" alt="pic_15" src="https://user-images.githubusercontent.com/47390680/54316773-d4b37680-45e1-11e9-8813-15a7d6d3cb9a.png">
<img width="721" alt="pic_16" src="https://user-images.githubusercontent.com/47390680/54316763-d3824980-45e1-11e9-9a5b-51e7f6324ed5.png">
<img width="721" alt="pic_17" src="https://user-images.githubusercontent.com/47390680/54316762-d3824980-45e1-11e9-8d5e-9daf2b039c5d.png">

**Comment by vitormhenrique** [comment]
have you tried to delete all settings? 
did it fix it?

**Comment by valepe** [comment]
Sorry for the delay. I'm quite busy in this period.
I did shutdown the system for some days and when I startup again to fix this problem, it was gone.
No more log errors. I don't know what happened.

**Comment by vitormhenrique** [comment]
Good!

**Comment by fjohannes** [comment]
I'm having the same issue here. Potentially leading to an extremely lagging Octoprint UI / Octoprint as whole.
Will try with deleting settings and see what happens..
[octoprint-logs.zip](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/7116577/octoprint-logs.zip)

**Comment by fjohannes** [comment]
After deleting all settings, the error was gone.
After re-implementing one Output (printer relay) it was still fine. After adding my DS18B20 temperature sensor, the issue reappeared. Maybe the sensor is broken, but it was reading plausible temp values nonetheless. Might change the sensor and test again..

**Comment by fjohannes** [comment]
The issue was reappearing. I sadly had to uninstall Enclosure Plugin for now.
One hint: Issue was appearing close after installing OctoKlipper Plugin. Maybe something weird going on between those two plugings? https://github.com/thelastWallE/OctoprintKlipperPlugin

**Comment by fjohannes** [comment]
When was trying to access my Octoprint this morning, I had a hard time because it was unresponsive for quite some minutes (even via ssh). After a while, I could access and checked the log, which gave some erors relating some phython2.7 files/folders missing in a directory named octoprint_enclosure.
e.g.:
IOError: [Errno 2] No such file or directory: '/home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/static/js/bootstrap-colorpicker.min.js'
Full log file attached.
[octoprint-logs (6).zip](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/7153674/octoprint-logs.6.zip)
How to repair this?
(when uninstalling Enclosure Plugin I choosed the option "including cleanup", btw.)
