### ISSUE TITLE
add input button no action

### ISSUE THREAD

**Issue by mcmasterp** [vitormhenrique/OctoPrint-Enclosure#23]
windows 10, firefox latest stable, no ad block etc. octoprint is on rpi3. 

Add output works fine. The first time I hit add input it closed the settings menu. every time since it just does nothing

**Comment by vitormhenrique** [comment]
It is probably because you have the development version, and your settings got messed up.... 

for now, until I publish the code, just send me emails instead of adding issues here.

Open your config.yaml file and delete everything under the
plugins:
  enclosure:

The file should be on ~/.octoprint
