### ISSUE TITLE
Lowerlimit for PWM

### ISSUE THREAD

**Issue by Tirpitz93** [vitormhenrique/OctoPrint-Enclosure#230]
Would it not make more sense to make the lower (temp a) a limit for the pwm?
In my case the pan doesn't like very low duty cycles. so using the lower temp as an absolute limit would make more sense,
If you wanted to have the pwm scale from 0 then set a temperature at which it would be zero as temp a.

for example:
![image](https://user-images.githubusercontent.com/6187560/55178941-511b8d00-517e-11e9-825c-8161bc052472.png)
in this case the fan would be completely off at temperatures below 25 deg, and jump straight to 40% when it reaches that temperature, scaling up to 34 deg for 100%.

**Comment by vitormhenrique** [comment]
I’m fine with this change. Thanks!
