### ISSUE TITLE
DHT11 not showing temp or humidity

### ISSUE THREAD

**Issue by bogaskilop** [vitormhenrique/OctoPrint-Enclosure#234]
**Describe the bug**
DHT11 not showing temp or humidity    its is setup for GPIO 4    and i also installed  
/Adafruit_Python_DHT/   and used  examples $ python AdafruitDHT.py 11 4
and in console it shows :
Temp=16.0*  Humidity=68.0%
in octoprint enclosure  tab it shows :  

Temp & Humidity | 0 °C | 0 %

i already uninstalled and installed this plugin few times  and restarted rpi but this doesn't solve the problem :(

**Comment by sajovicd** [comment]
Did you uncheck or check sudo in advance part of plugin?

**Comment by bogaskilop** [comment]
i have check  this

**Comment by bogaskilop** [comment]
now i uncheck this and it shows  uff  thx  a lot for pointing this

**Comment by sajovicd** [comment]
No problem.
