### ISSUE TITLE
How to control multiple GPIO with one output Octoprint button ?

### ISSUE THREAD

**Issue by ZorK766** [vitormhenrique/OctoPrint-Enclosure#237]
Hi Victor.

First, many thanks for this fantastic plugin.

Here, it's more a question than a issue:

I've connected an active low 4 relay board, 4 tactile switch and 4 led to my GPIO.
The goal is i can control 4 relay from Octoprint or from physicals buttons on my printer. And i want to have a status led for each relay.

I've manage to make all work like i wanted, so i can turn on and off each relay in octoprintor with one tactile switch for each. I've create two inputs for the same tactile switch GPIO, so one is linked to the output controling one relay and one is linked to the led's GPIO.  So if i press a tactile switch, one relay is toggling, the octoprint button status is toggling and my led also.

But if i use the control button output for a relay in octoprint, the relay toggle, but not the led of course. And my led is now not synchronised with the relay state...

I can't figure how to make the octoprint button toggle one relay AND one led at the same time...
Is there a way to make a Toggle Octoprint Button act on two GPIO at the same time, like with a coma ?

Any idea ?

Regards.

**Comment by vitormhenrique** [comment]
The best way is to use gcode output, and use a combination of gcode that will trigger all your other outputs, so you press one button that will send a gcode that will activate other stuff already configured on the enclosure. I use this on my setup!
