### ISSUE TITLE
Please provide an IFTTT HOWTO

### ISSUE THREAD

**Issue by timur-tabi** [vitormhenrique/OctoPrint-Enclosure#239]
Can you provide a step-by-step guide on how to use this plugin with IFTTT?  I created an IFTTT account, and I think I got my API KEY, but I am otherwise completely confused on how to use this service.

**Comment by vitormhenrique** [comment]
I'll put this on the wiki: https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/36#issuecomment-303856716
