### ISSUE TITLE
Temperature Control dropdown empty

### ISSUE THREAD

**Issue by mcmasterp** [vitormhenrique/OctoPrint-Enclosure#24]
when I check off temp control there's a small drop effect of maybe 50px but nothing shows up about choosing heating or cooling etc.

**Comment by vitormhenrique** [comment]
I think this is also related with the other issue, delete the lines and let me know....

**Comment by vitormhenrique** [comment]
Can you also test on different browser?

**Comment by mcmasterp** [comment]
yes. I just tried chrome and same issue. as well I notice the issue of add input reliably closes the settings window and refreshes the page

**Comment by vitormhenrique** [comment]
Probably issue on the development that was fixed on release. I could not reproduce the issue on my environment, and I think I fixed yours yesterday.
