### ISSUE TITLE
[FR] need SOC temperature "sensor" for precise cooling.

### ISSUE THREAD

**Issue by njozsef** [vitormhenrique/OctoPrint-Enclosure#243]
Hi Vitor!
Thanx the great job! Great for ABS and HIPS printing.

I need sensor for internal cpu (rpi) temperature on dropdown box. for cool the electronics.
Actually i measured motherboard temp.(ds18b20) but this not accurate.

"navbartemp" plugin displayed SOC temp, but only displayed.

Thank you.

Jozsef Nagy

**Comment by vitormhenrique** [comment]
This is duplicated, I plan to include this on a next revision, just don't know when that will be as I'm really busy with other projects,
