### ISSUE TITLE
No temperature data with DHT22

### ISSUE THREAD

**Issue by neovanmatix** [vitormhenrique/OctoPrint-Enclosure#249]
**Describe the bug**
I've attached a DHT22-Sensor to my Raspberry 3 with OctoPi and the Enclosure-Plugin, but it show's 0° and 0% humidity on the Webinterface.

The DHT22 is connected (like descriped in the screenshots) to 3,3V with resistor, Ground an GPIO 13 (BCM27).
I've installed the Adafruit-DHT-Library and be able to get the temperature on the CLI:
```
pi@octopi:~/Adafruit_Python_DHT/examples $ sudo ./AdafruitDHT.py 22 27
Temp=25.3*  Humidity=46.3%
```

The configured Input seems correct; also the BCM-Pin 27 (i'm using an relay as output for LED-Stripes; also configured with BCM-Pin and it's working).

![dht22](https://user-images.githubusercontent.com/3227004/61176855-533c1700-a5c8-11e9-928c-a08df286d73b.png)

![dht22_2](https://user-images.githubusercontent.com/3227004/61176865-88486980-a5c8-11e9-997d-9727db8598f6.png)

Any idea's, what the cause could be?

**Comment by vitormhenrique** [comment]
Disable sudo under the advanced section.

**Comment by neovanmatix** [comment]
Hello, 
thank you very much :-) I found the Debugging-Option in the Enclosure-Addon and also found a regarding Logentry in octoprint.log:

> 2019-07-13 22:36:08,335 - octoprint.plugins.enclosure - INFO - Sensor Intern Temperature: 0.0 humidity 0.0
> 2019-07-13 22:36:18,349 - octoprint.plugins.enclosure - INFO - Temperature dht cmd: sudo python /home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/getDHTTemp.py 22 27
> 2019-07-13 22:36:18,452 - octoprint.plugins.enclosure - INFO - Dht result:

After disabling sudo it's working now. Thank you! :-)
