### ISSUE TITLE
Typo in 3.1

### ISSUE THREAD

**Issue by rtheil** [vitormhenrique/OctoPrint-Enclosure#25]
Setting up input
Event type: printer
Printer action drop down: Says "Hise", should be "Rise"

**Comment by vitormhenrique** [comment]
haha... Thanks!
Fixed, just uninstall and install it again....

**Comment by rtheil** [comment]
Excellent! Just giving this a once-over. Waiting on some parts to expand my enclosure setup. Just got a filament sensor in the mail, and have another on the way. Will provide as much feedback as possible.

**Comment by vitormhenrique** [comment]
Cool, planing on adding few more features this weekend....
