### ISSUE TITLE
Mechanical Button to Jog X Y Z E

### ISSUE THREAD

**Issue by 407pilot** [vitormhenrique/OctoPrint-Enclosure#257]
**Describe the solution you'd like**
The ability to add a mechanical button that, when pressed, will move the axis a set distance and when held, will continuously "jog" an axis in the + or - direction. The axis should jog faster the longer the button is held. A max speed function for this would be useful. 

**Describe alternatives you've considered**
I've added a button that sends G91 G0 E0.1, but you have to press the button over and over for large movements. I also have load and unload filament buttons, but sometimes I just want more granular control.

**Comment by vitormhenrique** [comment]
what I suggest you yo do is create multiple buttons with different jogging dimensions, octoprint is not a real time system, so it would be pretty difficult to get this working perfectly, it would most likely just crash the machine.
I use the same feature, i have set ip up to move the axis 10cm...
