### ISSUE TITLE
Outputs - Temperature Alarm

### ISSUE THREAD

**Issue by Tropper71** [vitormhenrique/OctoPrint-Enclosure#258]
Hello,
I can`t select any "Controlled IO"! I see the Pulldown Menu but no entry or selection!
Regards
Ralf

![grafik](https://user-images.githubusercontent.com/55784194/65582240-51ee7980-df7d-11e9-9ef8-440d6d163df2.png)

**Comment by igorenot** [comment]
Do you have working outputs?

**Comment by vitormhenrique** [comment]
You have to configure outputs first....

**Comment by Tropper71** [comment]
How can I do this? Per PuTTy, Octoprint or config.txt and that is the syntax?
Thanks for your help.

**Comment by Tropper71** [comment]
How can I do this? Per PuTTy, Octoprint or config.txt and that is the syntax?
For example GPIO25 defined as OUT but the sane result.
![grafik](https://user-images.githubusercontent.com/55784194/65761613-6bc7c200-e11f-11e9-8c4e-b0a4ef5c22ac.png)

Thanks for your help.

**Comment by vitormhenrique** [comment]
Read the documentation on GitHub, you need to setup output on the enclosure
plugin.

**Comment by Tropper71** [comment]
" ...need to setup output on the enclosure..." Yes but how can I do this? I can`t find any solution.

**Comment by vitormhenrique** [comment]
I’m on vacation, setting up the plugin is very self explanatory, you add
outputs, or inputs, The same way you tried to configure the input you do
for the output....
read the configuration page on the enclosure settings.

**Comment by Tropper71** [comment]
Some things are so easy, sorry for the disturbance on your vacation! The problem is solved!
First of all I must generate a new output type **"Regular IO "** and then I can see and use this output in the menu **"Controlled IO"** of **"Temperature Alarm "**. OK now!

**Comment by vitormhenrique** [comment]
No worries! Glad you figure it out!
