### ISSUE TITLE
New sensor type

### ISSUE THREAD

**Issue by kyjak** [vitormhenrique/OctoPrint-Enclosure#264]
I have written a new sensor class for enclosure (SHT21), 
to fetch values from the "sensors" command.
I'd like to contribute, but have no idea on how to plug it in the code,
can someone help me/or I send the class to someone?
thx for clues

**Comment by vitormhenrique** [comment]
I actually just started rewriting most of the plugin, to be easier to maintain, so just put your code on a gist and i'll include on the next release.

**Comment by kyjak** [comment]
I managed to get it work, will make a PR to this repo
