### ISSUE TITLE
GPIO INPUT TO GCODE

### ISSUE THREAD

**Issue by davidcgu** [vitormhenrique/OctoPrint-Enclosure#269]
Good afternoon

I have installed 2 pushbuttons as GPIO inputs and wanted to find the way to run a Gcode when pushing each button however I don't see the way to move forward, the idea is to be able to load filament pushing one button and unload with the other push button.

Any help is wellcome.

Thanks in advance

**Comment by jessaskey** [comment]
From my understanding of the plugin, you would make a new OUTPUT of type GCODE (with your GCODE specifics)... then define an INPUT to the wired up GPIO input with the appropriate (pull-up) and  falling edge if your switch goes to ground)... the last part of the INPUT definition is the OUTPUT you want to trigger... that would cause the button to send a GCODE.

I have some similar setups, my OUTPUTS run python scripts... however I have had trouble with the INPUTS not working consistently. One of the configuration options is the put a button in the UI for the OUTPUT, those buttons works all the time.. however, pressing the button (and confirming that it is pulling the signal low on the GPIO pin) sometimes wont trigger the INPUT. I have not been able to solve this issue so if anyone else has any ideas, please post them here too (sorry, not trying to hijack this issue).

**Comment by davidcgu** [comment]
I'm curious to see not too many people commented on this post, for me looks a very interesting feature, adding capability to wire a push button that runs whatever gcode/script you wanted.... 

For me it's very interesing, can put many examples, as instance having a push button that tongle the cabin light on/off, but can imagine tons of useful aplications...

Regards

**Comment by vitormhenrique** [comment]
As @jessaskey commented, you cana already to what you want, I have multiple push buttons that send g-code comments to my printer, you setup an OUTPUT with the g-code that you want, and you trigger if using an input.
I have g-codes to move the read around, connect the printer, lights, etc....

**Comment by davidcgu** [comment]
> As @jessaskey commented, you cana already to what you want, I have multiple push buttons that send g-code comments to my printer, you setup an OUTPUT with the g-code that you want, and you trigger if using an input.
> I have g-codes to move the read around, connect the printer, lights, etc....

Most probably there is somehting I'm missing but can't find the way to link an input to trigger and send an specific gcode, can you be so kind to bring me some light?  

Much appreciated in advance

**Comment by vitormhenrique** [comment]
First create an OUTPUT with the g-code that you want to execute, give it a name, on my example, "extrude 50mm"

<img width="715" alt="Screen Shot 2020-03-20 at 11 57 33 AM" src="https://user-images.githubusercontent.com/3967383/77187286-397d9880-6aa2-11ea-8cca-ac09b39678ff.png">

Than create an INPUT and select "output control" and select the output created on step 1.

<img width="665" alt="Screen Shot 2020-03-20 at 11 58 28 AM" src="https://user-images.githubusercontent.com/3967383/77187383-60d46580-6aa2-11ea-89c9-ac4651ea3862.png">

**Comment by davidcgu** [comment]
Amazing!!!!!!!  thank a lot

Just one question, in case of having more than one, what it makes the link between the Gcode output and one specific input?

Regards

**Comment by davidcgu** [comment]
Forget it, I see, it's the output label.

Many thanks Victor.

Un saludo desde Barcelona, espero que tu y tu familia esteis bien considerando la situación que tenemos actualmente.
