### ISSUE TITLE
Instructions missing for accessing GPIO

### ISSUE THREAD

**Issue by cmgerdes** [vitormhenrique/OctoPrint-Enclosure#273]
I've ran into this issue twice.  First when I first installed the plugin, then after when I had my sd card go bad and had to rebuild from scratch (this was a couple months ago).  

It appears that you need to enable non-sudo access on the pi in order for the plugin to work.  I can confirm at the very least I had to do this when Installed about 2 months ago from scratch.

Unfortunately, I didn't note down the exact steps I followed to fix this, but I believe what I did was this: https://raspberrypi.stackexchange.com/questions/40105/access-gpio-pins-without-root-no-access-to-dev-mem-try-running-as-root

So, I recommend adding the following step to the setup steps for the instructions:
`sudo adduser pi gpio`

You may also need to do this:
```
sudo chown root.gpio /dev/gpiomem
sudo chmod g+rw /dev/gpiomem
```

I plan on upgrading to a rpi 4 in the near future so I'll get a chance to confirm then that this is still an issue (I expect it will be) and exactly what needs to be done to fix it.

**Comment by vitormhenrique** [comment]
yeah, it really depends on how you install and get octoprint on your system, are you using octopi?

Thanks for coming back and documenting.
