### ISSUE TITLE
Timelaps

### ISSUE THREAD

**Issue by bar2104y** [vitormhenrique/OctoPrint-Enclosure#278]
For time laps....
On AUTOHOME in GCODE  high signal to relay module(for 12V les) and snapshot on pro camera(high signal to second relay). It is like remote pult for cameras like this. Can you do it or help me create this plugin.(get tutorials)
![image](https://user-images.githubusercontent.com/33576679/70853517-07b3cf00-1ec0-11ea-831f-2ab0abb37006.png)

**Comment by vitormhenrique** [comment]
You could add gcodes on this plugin to enable an output gpis that would trigger the remote and take a picture.

https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/G-CODE-Control

You would need to automate having this gcode every layer, but it is doable.
