### ISSUE TITLE
Temperature and humidity in the navbar?

### ISSUE THREAD

**Issue by NiklasOlofsson** [vitormhenrique/OctoPrint-Enclosure#28]
Hello,

Could the temperature and humidity be shown like this:
<img width="494" alt="octoprint_-_google_chrome_2017-04-16_12-35-32_04352082" src="https://cloud.githubusercontent.com/assets/4583709/25070543/ce0eaefe-22a1-11e7-8278-7fbb7bbff7a6.png">

Maybe the possibility to set the names for the two values yourself (to make it fit)? Like T: 22C H: 35%
The "Navbar Temperature Plugin" shows the Pi temperature.

**Comment by vitormhenrique** [comment]
I'll double check to see if adding a new item to the navbar works together with the "Navbar Temperature Plugin", if not I'll re-implement everything on my plugin....
I'll only be able to check this the following weekend....

**Comment by vitormhenrique** [comment]
added on 3.5

**Comment by NiklasOlofsson** [comment]
Is it possible to turn it off if you need to?

**Comment by vitormhenrique** [comment]
Not yet, but i can add it on next release....

Best regards,
Vitor Henrique

**Comment by vitormhenrique** [comment]
3.51 you can turn it off on advanced settings....
