### ISSUE TITLE
DHT22 not showing  0 °C and 0 %

### ISSUE THREAD

**Issue by Lino77** [vitormhenrique/OctoPrint-Enclosure#281]
hello the temperature is not shown in the dash what am I doing wrong

![Auswahl_001](https://user-images.githubusercontent.com/11890989/71546008-684c0d00-2992-11ea-9272-2e1030f317f1.png)
![Auswahl_003](https://user-images.githubusercontent.com/11890989/71546011-6b46fd80-2992-11ea-9d12-8677c00fe80f.png)

pi@octopi:~/Adafruit_Python_DHT/examples $ ./AdafruitDHT.py 22 4
Temp=21.7*  Humidity=35.1%

**Comment by vitormhenrique** [comment]
Read the troubleshooting guide.

**Comment by Lino77** [comment]
DHT Sensor works outside of the plugin but does not show any value on the plugin: Disable "use sudo" under the advanced section of the plugin
