### ISSUE TITLE
AM2303 showing 0 °C and 0 %

### ISSUE THREAD

**Issue by EnYo15** [vitormhenrique/OctoPrint-Enclosure#284]
The temperatures in shows 0 °C and 0 %

sudo ./AdafruitDHT.py 2302 16 is giving me proper response and i disabled sudo to run python commands in the advanced options. Jet the log sais 

octoprint.plugins.enclosure - INFO - Failed to execute python scripts, try disabling use SUDO on advanced section of the plugin.

how can i solve this problem

**Comment by vitormhenrique** [comment]
read the log....

octoprint.plugins.enclosure - INFO - Failed to execute python scripts, **try disabling use SUDO on advanced section of the plugin**.

**Comment by EnYo15** [comment]
I disabeld sudo in advanced settings and stilll get this Message!

**Comment by vitormhenrique** [comment]
try restarting your pi....

**Comment by EnYo15** [comment]
I restarted with both Software Options, I repluged the power and in reinstalled the Plugin.
The only thing I did not, was to reinstall OctoPrint

**Comment by EnYo15** [comment]
now my octoprint.log file gives two errors

2020-01-25 11:07:10,339 - octoprint.plugins.enclosure - INFO - Failed to execute python scripts, try disabling use SUDO on advanced section of the plugin.
2020-01-25 11:07:10,341 - octoprint.plugins.enclosure - WARNING - An exception of type ValueError occurred on log_error. Arguments:
('need more than 1 value to unpack',)

again I unchecked Use Sudo in the advanced options and i restartet my pi multiple times

**Comment by vitormhenrique** [comment]
Have you figured this out?

Try disabling sudo password:

```
sudo visudo
and add pi ALL=(ALL) NOPASSWD: ALL to the end of the file.
```

**Comment by EnYo15** [comment]
I did try this as well.
I had to reinstall Octoprint and now it works.
