### ISSUE TITLE
BeagleBone

### ISSUE THREAD

**Issue by manbehindthemadness** [vitormhenrique/OctoPrint-Enclosure#290]
Does this plugin work with systems running on BeagleBone? If so what is the procedure? If not please classify as a feature request.

**Comment by vitormhenrique** [comment]
Hello,

Unfortunately, this will not work on beagle bones, The source code would need a significant re-write to work on multiple SBC's and I started my masters and don't have much time to work on non-priorities feature requests.

Given that an RPI4 is definitely capable of handing octoprint and it is fairly cheap I'm not inclined to port it.

That being said, source code is open source, so feel free to port it :)

**Comment by manbehindthemadness** [comment]
﻿
> 
> Oh well, thanks for letting me know!
