### ISSUE TITLE
Enclosure Plugin is blank after Fresh Install

### ISSUE THREAD

**Issue by txbone66** [vitormhenrique/OctoPrint-Enclosure#293]
**Describe the bug**
I'm new to Raspberry and Octoprint, so I'm sure it's an Ido3t error, but to offset your frustration, I've sent some $ to buy a pint.  Octopi is running, but when I install the Enclosure Plugin from the plugin manager, this is the screen that I see.  
![Screen Shot 2020-02-29 at 9 14 25 AM](https://user-images.githubusercontent.com/16477443/75610110-f8621c00-5ad3-11ea-8e20-67310a86caa6.png)

I've uninstalled, reinstalled, and rebooted, but I get the same result.  I'm wanting to use this to send a GPIO command to a power block that will turn the printer and lights on and off.

[octoprint.log](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/4270473/octoprint.log)

**To Reproduce**

**Expected behavior**

**Additional context**
Add screenshots of your settings screen, so I know how to recreate the data. Also enable the debug information under the advanced section of the plugin, reproduce the issue and attach the [octoprint log](https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299) here.

**Comment by txbone66** [comment]
like I said, Ido3t error.

**Comment by vitormhenrique** [comment]
I guess you found the configuration screen? ;)

**Comment by txbone66** [comment]
Yep!  something simple!  I swear I spent a long time reading and checking, but all this is so new to me, I just missed that.
