### ISSUE TITLE
IFTTT malformed message 

### ISSUE THREAD

**Issue by GpMissi** [vitormhenrique/OctoPrint-Enclosure#295]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34158856/75682428-b4b71000-5c95-11ea-9192-aab77fc156fe.png)

**Comment by GpMissi** [comment]
Sorry, my error

**Comment by vitormhenrique** [comment]
If you don’t mind, explain how you fixed the issue, so people could find this and figure out their issue as well. :)

**Comment by GpMissi** [comment]
Yes, sorry

**Comment by GpMissi** [comment]
I don't know how to format the message that the plugin sends to IFTTT before passing it on to Telegram. But obviously it's my problem. Perhaps the message sent to IFTTT contains redundancy

**Comment by GpMissi** [comment]
(i apologize for my english, i am using google translator)
