### ISSUE TITLE
Pulse sensor for filament jam

### ISSUE THREAD

**Issue by Eisbaeeer** [vitormhenrique/OctoPrint-Enclosure#298]
I printed an optical sensor who creates pulses, when the filament will be transported. In this case you are able to get filament jam, if the hotend is filled or any other errors. It will be nice, if I can pause the print, if the pulses are missing at a configurable time. I use a GPIO of RPI as input.

**Comment by vitormhenrique** [comment]
Duplicated:

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/122
