### ISSUE TITLE
RC servo control,, and  enclosure temp view on temperatures page

### ISSUE THREAD

**Issue by jaygrovr** [vitormhenrique/OctoPrint-Enclosure#319]
Wanted to know if you can do some RC servo control through your interface.  I would mainly be wanting to use this to control some vent openings, so that I can cool down my enclosure after a print, so the servos would want to get turned on a move to a set position.  This could be gcode.  I dont have any outputs on my controller board for servos at this point.

I also wanted to know if you could put the temperature of the enclosure on the temperatures page, so that it would be easy to monitor and graph temps of the enclosure when using heating or cooling.

**Comment by vitormhenrique** [comment]
https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/294

**Comment by vitormhenrique** [comment]
https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/34

**Comment by vitormhenrique** [comment]
please search issues before opening new ones, that is common best practice on GitHub, we spend a lot of time writing free code for you, and only request doing some 2 minute search before asking the same question again.

**Comment by jaygrovr** [comment]
Yes I did, but wasnt exhaustive enough.  Sorry for the extra work.
Jason
    On Tuesday, May 26, 2020, 01:45:51 PM PDT, Vitor de Miranda Henrique <notifications@github.com> wrote:  
 
 


please search issues before opening new ones, that is common best practice on GitHub, we spend a lot of time writing free code for you, and only request doing some 2 minute search before asking the same question again.

**Comment by vitormhenrique** [comment]
no worries, well, follow those threads with updates whenever I have the change they will be implemented.
