### ISSUE TITLE
Trigger PSU Plugin via API

### ISSUE THREAD

**Issue by Tobias0044** [vitormhenrique/OctoPrint-Enclosure#320]
I would like to execute a shell command as output to activate the PSU plugin via API. However, the entire website freezes until I kill the process via SSH.
My command: curl -s -H "Content-Type: application / json" -H "X-Api-Key: 1AFD0CXXXXXXXXXXXXXXXXXXXX1B11" -X POST -d '{"command": "togglePSU"}' http: // octopi / api / plugin / psucontrol

If I execute the command via SSH everything works.
I tried to do it in a .sh file, but the same thing happens

**Comment by vitormhenrique** [comment]
logs? print screens? 

my best guess as you didn't provide the requested documentation when opening the issue, and probably didn't look at the closed issues as well: your command takes a while to execute and it locks the execution of the plugin, you can't do that, you need to execute the command on the background, most times you can just add an "&" at the end of the command, sometimes you need to pipe result somewhere.

**Comment by Kerjox** [comment]
Hi, I have had the same problem when I try to use PSUcontrol and Enclosure with the script:

> `curl -s -H "Content-Type: application / json" -H "X-Api-Key: 1AFD0CXXXXXXXXXXXXXXXXXXXX1B11" -X POST -d '{"command": "togglePSU"}' http://0.0.0.0/api/plugin/psucontrol`

If you are **testing the scritp whith the buttons of the octopi interface**, it makes hang the web interface.
![image](https://user-images.githubusercontent.com/60511422/93000515-3e8b4400-f529-11ea-9414-56f2ece42158.png)

But don't worry, your script is not wrong, simply the button of the web interface is completely broke.

So the **way to make it work** is testing it with a pysical button, and surprisingly, it works perfectly.

Screenshot to the config of the script:
![image](https://user-images.githubusercontent.com/60511422/93000792-ea815f00-f52a-11ea-8a1e-48d05b716010.png)

And the Input associated:
![image](https://user-images.githubusercontent.com/60511422/93000816-0e44a500-f52b-11ea-8366-349bd1b4e543.png)
![image](https://user-images.githubusercontent.com/60511422/93000822-16044980-f52b-11ea-94c9-6e104f554b0c.png)
You can also see the electrical schema in this thingi [here](https://www.thingiverse.com/thing:4024711)

And of corse, the script:

`curl -s -H "Content-Type: application/json" -H "X-Api-Key: 1AFD0CXXXXXXXXXXXXXXXXXXXX1B11" -X POST -d '{ "command":"togglePSU" }' http://0.0.0.0/api/plugin/psucontrol 
echo 'Botón de encendido pulsado manualmente'`

This script make a notification in your octopi web interface that says "Botón de encendido pulsado manualmente":
![image](https://user-images.githubusercontent.com/60511422/93001033-66c87200-f52c-11ea-814d-1862d055dfd5.png)
