### ISSUE TITLE
Graphical Inputs

### ISSUE THREAD

**Issue by duennerd** [vitormhenrique/OctoPrint-Enclosure#324]
Hi 
I like your plugin very much. It has a lot of potential. I was trying do do an enclosure control system with an Arduino Uno. But as I started using octoprint I thouhgt to integrate it into the raspberry. 
I then saw your great plugin. 
So I was wondering if it would be possible to add the feature to add an graphical input field. 
My idea is to have a temperature sensor and a heat fan (or a hair dryer). In the interface I would set the ambiant temperature of the enclosure to 45° for example. Everytime the temperature in the enclosure from the sensor goes under 45° the fan is triggered for like 60 seconds. (Or just when the heat is 50°.) I could then control the temperature in the enclosure. 
In my application I had a potentiometer for setting the desired temperature but the raspberry doesnt have analog input. But with a digital input field inside octoprint, I think it should work.

**Comment by vitormhenrique** [comment]
there is no need to have a time limit on the heater, the software controls the temperature on a target value already, much better than a time control.
Also charts already have been requested, and there is a long explanation on what needs to be changed on octoprint first so I could implement that.
