### ISSUE TITLE
Can't contril pin 28

### ISSUE THREAD

**Issue by albebert** [vitormhenrique/OctoPrint-Enclosure#326]
**Describe the bug**
need to use pin 28 to control simple relay but can't error in octoprint log : 

 octoprint.plugins.enclosure - WARNING - An exception of type ValueError occurred on log_error. Arguments:
('The channel sent is invalid on a Raspberry Pi',)

**To Reproduce**
add an output on gpio pin 28 

*Additional context*

tested with gpio command  : 

gpio mode 31 out
gpio write 31 1
gpio write 31 0

and all is working

**Comment by oblivionratula** [comment]
Well 27 is the highest GPIO pin, isn’t it? So as the error states, 28 is invalid. If you mean physical pin 28, that’s GPIO 1 according to what I’m looking at, and that may conflict with ID_SC.

But I’m no expert.

**Comment by albebert** [comment]
yes i speak about pin N° 28;

but when i use the gpio from cli all is working so i d'ont understand why with enclosure plugin they don't work

**Comment by vitormhenrique** [comment]
please, follow instructions on the troubleshooting guide... and instructions on how to open an issue.

Asking for questions with no log, no print screens does not help and makes impossible for anyone to help...

<img width="947" alt="Screen Shot 2020-05-26 at 3 20 09 PM" src="https://user-images.githubusercontent.com/3967383/82946678-66e43800-9f64-11ea-9693-e1b5213f89fe.png">

**Comment by vitormhenrique** [comment]
https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/Troubleshooting-Guide#open-a-new-issue

**Comment by vitormhenrique** [comment]
you are globally using incorrect names for the pin based on your message, read instructions or follow the guide on how to ask queens, closing for now
