### ISSUE TITLE
[Feature Request] CircuitPython library for DHT sensor - Python 3

### ISSUE THREAD

**Issue by robertomilan** [vitormhenrique/OctoPrint-Enclosure#343]
Hello,
hope to find you good!
Due to the deprecated Adafruit Python DHT Sensor Library I think it could be great to update to the CircuitPython library: https://learn.adafruit.com/dht-humidity-sensing-on-raspberry-pi-with-gdocs-logging/python-setup

Thanks

Ron

**Comment by vitormhenrique** [comment]
that is the way I'm gonna do, BUT, CircuitPython is not compatible with python 2, and the pluging will stop working on old systems...

You can track progress here...

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/302
