### ISSUE TITLE
Python 2.7 reached the end of its life on January 1st, 2020

### ISSUE THREAD

**Issue by n3roGit** [vitormhenrique/OctoPrint-Enclosure#351]
Can the new Adfruit package also be used for the temperature sensors?

https://learn.adafruit.com/dht-humidity-sensing-on-raspberry-pi-with-gdocs-logging/python-setup

**Comment by vitormhenrique** [comment]
Looks like you have been using git for a while, i would expect at least searching for issues before opening two new ones basically with the same request....

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/302
