### ISSUE TITLE
Feature Request : humidity based control of relay

### ISSUE THREAD

**Issue by manroop5** [vitormhenrique/OctoPrint-Enclosure#361]
Is it possible to use this plugin for humidity based control (input from sensor) of a relay which turn on and off the power to the filament dehydrator with a feedback loop?

high humidity ---> triggers the relay to turn on dehydrator till desired humidity achieved (like PSU control plugin)
Also which sensor would be ideal to sense humidity

**Comment by vitormhenrique** [comment]
already there....  just read again the settings and you will figure it out how to do it...
