### ISSUE TITLE
[Feature Request] Idle timer

### ISSUE THREAD

**Issue by TazerReloaded** [vitormhenrique/OctoPrint-Enclosure#377]
**Is your feature request related to a problem? Please describe.**
I control lights and the printers PSU with the Raspberry Pi GPIO. There is already an option to trigger on finished prints, but I'd like to propose another feature to prevent leaving the lights on.

**Describe the solution you'd like**
A simple timer that gets reset with every command sent to the printer. The user can configure the time in seconds, and when the timeout is reached without any commands (Printer is certainly inactive), the output gets switched off. The timer is also reset by manual movements or heater commands, so if I calibrate something and the printer is not actively printing, it won't shut off.

**Describe alternatives you've considered**
There is the "Lights out" plugin which provides just that feature, but it can only send a GCode-Command when the timer elapses. Setting separate timers for different outputs would also be useful.
An additional option would be to watch the reported heater temperature, and only shut off when it is below a defined threshold. This would prevent accidental shutdown during heating, but would also make it possible to forget the printer with active heaters (not good!).
Another trigger could be if an user is viewing the WebUI (WebSocket open), OctoPrint writes those events to its log, so there should be a possibility to catch them. This way we could only switch the lights on and start the webcam stream when an user is active, and save power and CPU otherwise.

**Additional context**
This feature is already implemented for the plugin "PSU Control" (https://plugins.octoprint.org/plugins/psucontrol/), where it worked quite well. But I'd like to use that feature on not just the PSU, and "PSU Control" is still relatively buggy, so I want to replace it with the enclosure plugin.

**Comment by vitormhenrique** [comment]
there are several ways to accomplish this already, and on the new version will also have another one.

For lights there is already an "auto shutdown" with delays, so when the printer is complete the gpio will shutdown automatically.

I don't understand the heater example, as it also has an auto shutdown when printer is complete, so if you want to make sure that heater is off when the printer is done just select "auto shutdown" for that heater.

Plugin also has ability to shutdown when the printer is canceled or fails.

The new release will also have individual scheduling systems, so if you for example wants to disable "lights" at light automatically you will be able to do that.

I think that for now this is enough set of features and I'm not planing to add watchdogs for every input. So for now I'm not going to add this to the feature request, if more people end up here and find this useful i might consider in the future.

Of course I welcome you or any other developer to implement said feature and I'll gladly merge it here.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/3967383/104151318-54f3c000-53a2-11eb-8951-6e98523756b4.png">
