### ISSUE TITLE
Turn off temperature control from GPIO input

### ISSUE THREAD

**Issue by rbauwens1** [vitormhenrique/OctoPrint-Enclosure#38]
Would it also be possible to add functionality to shut off the heater/temperature control from the GPIO input? I've added a smoke detector to my enclosure and would like to be able to shut off both the printer as well as the heater if smoke is detected.

**Comment by vitormhenrique** [comment]
I'll work on that... 
for now, you can add the heater to a to a second relay, and control this new relay using the event, it sucks, but possible...

**Comment by rbauwens1** [comment]
Thanks for the work around, I'll try that out.

**Comment by vitormhenrique** [comment]
added on 3.5
