### ISSUE TITLE
Control a pin based on another output value

### ISSUE THREAD

**Issue by berretto** [vitormhenrique/OctoPrint-Enclosure#382]
Sorry if it is a silly question.

I want to control an rgb led with 3 raspberry output to indicate different situations (ex: power on, relay 1 on and relay 2 on).

It is possible to make an output value to be dependent on another output value?

Ex relay on pin 21 is on with logic ‘0’ and I want to set pin 20 to logic ‘1’ to turn on led.

even with a script could be ok.

Ale

**Comment by vitormhenrique** [comment]
for a simple LED you really don't need another gpio to turn a LED when you turn a relay on, on your example, you could just add an LED on the same pin 21 with an active low circuit, so when you turn the relay on the 21 on by driving it low, you will also turn an LED on.

To answer your question the way that you could do it now is by creating all the outputs (relay, and led) ->
create another output that is a gcode command that triggers the relay and the led ->
create an input that when pressed activates the gcode command
