### ISSUE TITLE
Plugin works, temp sensor and heater work.  Can't control from main ui

### ISSUE THREAD

**Issue by schmooot** [vitormhenrique/OctoPrint-Enclosure#385]
**Describe the bug**
I've got the plugin installed and working with my temp sensor and a heater circuit.  I can see the current temp and control it from the plugin page as per the picture.  

![temp control](https://user-images.githubusercontent.com/46872275/104974876-09e33980-59ae-11eb-82bf-b3500c65aaa3.jpg)

However on the octoprint temp page it displays no data and no available preset option to turn it on
![set temp](https://user-images.githubusercontent.com/46872275/104974873-094aa300-59ae-11eb-83b1-c0b220bc5e86.jpg)

I can preheat the chamber from the plugin setting but as soon as I start a print it defaults to the presets of course.

In the main settings under the presets I can add and modify new presets but don't get the enclosure temp option

![presets](https://user-images.githubusercontent.com/46872275/104975161-c2a97880-59ae-11eb-9ac2-78b730c090a6.jpg)

I feel I am just missing some simple checkmark somewhere but can't find anything.

**Comment by vitormhenrique** [comment]
Hello,

Octoprint Enclosure plugin has absolutely nothing to do and no integration with the chamber that you are seeing on the temperature tab, all settings for this plugin are on the enclosure tab, all default values and all configurations on the settings of this plugin.

You can set a default temperature on the settings and have the plugin auto start and auto stop the heating on the settings but there is no way to do this over the temperature tab.

Vitor Henrique
