### ISSUE TITLE
[Bug] Settings page does not close after clicking on "Close" or "Save" with Python 3

### ISSUE THREAD

**Issue by fnsign** [vitormhenrique/OctoPrint-Enclosure#386]
I recently upgraded Octoprint to Python 3 and discovered that now the settings page won't close when hitting the "Close" or "Save" button, though the settings are being saved normally. It only closes if if use the "X" in the upper right corner or click outside the settings page. 
I disabled all my plugins and enabled them 1 by 1 and found that the Enclosure plugin is causing that issue. Reproduced it with Safari 14.0.2 and latest Google Chrome browser.

Enclosure Plugin: v 4.13.1
OctoPrint 1.5.2/1.5.3
Octopi: 0.17.0
Python 3.7.3

**Comment by vitormhenrique** [comment]
the plugin it's not compatible with python 3.7 as mentioned here https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/302.

Working on it, probably months to be available.
