### ISSUE TITLE
Adding Blob detection.

### ISSUE THREAD

**Issue by ChrisP-Git** [vitormhenrique/OctoPrint-Enclosure#39]
Hi,

I'm actually designing a blob detection ( https://github.com/ChrisP-Git/BlobDetector ) that detects if the print get unstuck from the bed and stick to the nozzle, which will create a plastic blob that can detroy extruder wiring. 

The thing is based on a laser barrier managed by an arduino that will trigger a digital port in case of obstruction. In this case, the print should be stopped. It's different from end of filament detection where the print should be paused.

What would be perfect would be an additionnal action with specific GPIO port.

Would that be possible, or even make sense to you ?

**Comment by vitormhenrique** [comment]
I guess I just need to create another type of action with stop, instead of pause, and filament change.

Simple enough...

**Comment by ChrisP-Git** [comment]
Great :) Take your time, there's no urgency, I do not have much free time to work on my detector right now, but I wanted to ensure that there's a viable roadmap
 ;)

**Comment by vitormhenrique** [comment]
Added on 3.5
