### ISSUE TITLE
Mail notification in case of filament runout?

### ISSUE THREAD

**Issue by Boby71** [vitormhenrique/OctoPrint-Enclosure#41]
Hi, I love your plugin - and I just asked myself if it's possible to add/configure an email notification as soon as the filament sensor got activated? Thank you!

**Comment by vitormhenrique** [comment]
You already can do this using [IFTTT](https://ifttt.com).

Steps to configure:

Login / Create an account on IFTT.

Go to My Applets, create a new applet and select Maker Webhooks after clicking "This". Give access to the maker channel. Select "Receive a web request" and you need to specify a name for the event, I used "printer_event" I think you can not have a empty space here.
For that "That" part I'm using a Send a notification from the IFTTT app (but anything else should work, like an email, another app push notification). For the content use the following: {{EventName}} : {{Value1}} .

After you set up your applet you can test it clicking on your username on the top right, services, click on the maker webhooks and click documentation.
A web page with your key and a test button will show up. Fill up the {event} with the same name that you gave it before, my case printer_event and on the "value1" write something like: This is a test.

Click test it, it should notify your client / send an email or whatever else you configured. My experience is that it took 5 minutes to start working, but after you get it working there it should work fine on the plugin as well.

If you got it working, just go back to the plugin enclosure, advanced section, enable the notification and add the IFTT maker key, and the event name that you gave. That is it.
