### ISSUE TITLE
OctoPrint-Enclosure 4.13.1 does not install correctly from plugin repo with octopi 0.18.0

### ISSUE THREAD

**Issue by mcginnisa** [vitormhenrique/OctoPrint-Enclosure#440]
**Describe the bug**
After installation using OctoPrint GUI and system reboot, OctoPrint-Enclosure does not show up in the plugin list and no evidence that it has been installed can be found anywhere in the OctoPrint GUI. Also after installing the confirmation dialog refers to the plugin as unknown.

**To Reproduce**
Install fresh octopi and upgrade to 0.18.0
Install OctoPrint-Enclosure 4.13.1 from the plugin repository using the octoprint GUI

**Expected behavior**
OctoPrint-Enclosure installs successfully and is shown in the installed plugin list in octoprint after reboot

**Additional context**
I am using the following versions:
octoprint 1.7.0
python 3.7.3
octopi 0.18.0
OctoPrint-Enclosure 4.13.1
Raspberry Pi 3B+ with brand new SD card and 3.5A power supply with extremely short and high gauge USB cable

I am able to install Fullscreen Plugin (0.0.6) just fine and it is displayed in the installed plugin list and works as intended

![image](https://user-images.githubusercontent.com/27945597/137675714-0ce12072-03f4-4415-846f-5483e5319993.png)
![image](https://user-images.githubusercontent.com/27945597/137675729-30cfe072-e143-4340-843e-cd3eb49cb6c3.png)

Install log:

`Installing plugin "OctoPrint-Enclosure" from https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/master.zip.../home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmp_7q5bmqp/OctoPrint-Enclosure-master.zip --no-cache-dirLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simpleProcessing /tmp/tmp_7q5bmqp/OctoPrint-Enclosure-master.zipRequirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Enclosure==4.13.1) (1.7.0)Requirement already satisfied: RPi.GPIO>=0.6.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Enclosure==4.13.1) (0.7.0)Requirement already satisfied: requests>=2.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Enclosure==4.13.1) (2.26.0)Requirement already satisfied: smbus2>=0.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Enclosure==4.13.1) (0.4.1)Requirement already satisfied: charset-normalizer~=2.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from requests>=2.7->OctoPrint-Enclosure==4.13.1) (2.0.7)Requirement already satisfied: idna<4,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests>=2.7->OctoPrint-Enclosure==4.13.1) (2.10)Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.7/site-packages (from requests>=2.7->OctoPrint-Enclosure==4.13.1) (1.26.2)Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests>=2.7->OctoPrint-Enclosure==4.13.1) (2020.12.5)Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.1.1)Requirement already satisfied: PyYAML<6,>=5.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (5.4.1)Requirement already satisfied: pathvalidate<3,>=2.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2.5.0)Requirement already satisfied: pkginfo<2,>=1.7.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.7.1)Requirement already satisfied: flask<2,>=1.1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.1.4)Requirement already satisfied: tornado<7,>=6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (6.1)Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.4)Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2020.11.13)Requirement already satisfied: unidecode in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.4.21)Requirement already satisfied: colorlog<6,>=5.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (5.0.1)Requirement already satisfied: immutabledict<3,>=2.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2.2.1)Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (3.1.1)Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.1.0)Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.10.4)Requirement already satisfied: cachelib<0.2,>=0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.1.1)Requirement already satisfied: netaddr<0.9,>=0.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.8.0)Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2021.2.23)Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (7.1.2)Requirement already satisfied: Jinja2<3,>=2.11.3 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2.11.3)Requirement already satisfied: feedparser<7,>=6.0.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (6.0.8)Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.18.2)Requirement already satisfied: OctoPrint-PiSupport>=2021.8.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2021.8.2)Requirement already satisfied: sentry-sdk<2,>=1.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.4.3)Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.5.0)Requirement already satisfied: psutil<6,>=5.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (5.8.0)Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.2.0)Requirement already satisfied: wrapt<1.13,>=1.12.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.12.1)Requirement already satisfied: emoji<2,>=1.4.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.6.1)Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.0.7)Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (3.5)Requirement already satisfied: sarge==0.1.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.1.6)Requirement already satisfied: netifaces<1,>=0.11 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.11.0)Requirement already satisfied: zipstream-new<1.2,>=1.1.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.1.8)Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2021.10.11)Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2.0)Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (2.8.5)Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.0.0)Requirement already satisfied: websocket-client<1,>=0.59 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.59.0)Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (1.0.1)Requirement already satisfied: zeroconf<0.34,>=0.33 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Enclosure==4.13.1) (0.33.4)Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-Enclosure==4.13.1) (0.1.2)Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.8->OctoPrint->OctoPrint-Enclosure==4.13.1) (1.0.0)Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-Enclosure==4.13.1) (2.0)Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Enclosure==4.13.1) (2020.5)Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Enclosure==4.13.1) (2.9.0)Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python3.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoPrint-Enclosure==4.13.1) (51.1.2)Requirement already satisfied: six in /home/pi/oprint/lib/python3.7/site-packages (from websocket-client<1,>=0.59->OctoPrint->OctoPrint-Enclosure==4.13.1) (1.15.0)Requirement already satisfied: ifaddr>=0.1.7 in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.34,>=0.33->OctoPrint->OctoPrint-Enclosure==4.13.1) (0.1.7)Building wheels for collected packages: OctoPrint-EnclosureBuilding wheel for OctoPrint-Enclosure (setup.py): startedBuilding wheel for OctoPrint-Enclosure (setup.py): finished with status 'done'Created wheel for OctoPrint-Enclosure: filename=OctoPrint_Enclosure-4.13.1-py3-none-any.whl size=71002 sha256=626bfd052d4af09ef497ba0a9ef12d7bcff07ade66a0c20542fbaffbf71daafcStored in directory: /tmp/pip-ephem-wheel-cache-lfjmidcn/wheels/83/a3/f1/6310d4b4e6e63f298a2ef3ca4bdbd1bac808308c24f1c94341Successfully built OctoPrint-EnclosureInstalling collected packages: OctoPrint-EnclosureAttempting uninstall: OctoPrint-EnclosureFound existing installation: OctoPrint-Enclosure 4.13.1Uninstalling OctoPrint-Enclosure-4.13.1:Successfully uninstalled OctoPrint-Enclosure-4.13.1Successfully installed OctoPrint-Enclosure-4.13.1Done!`

**Comment by X10SIV** [comment]
i have the same issue

**Comment by vitormhenrique** [comment]
I think there was an issue with one pull request missing a library on the setup, i fixed it now
