### ISSUE TITLE
Multiple DS18B20 working with OctoPrint-Enclosure - anyone got this working?

### ISSUE THREAD

**Issue by LightningShark25** [vitormhenrique/OctoPrint-Enclosure#445]
Hi has anyone managed to get multiple DS18B20 working with Octopi/Octoprint?
I got one sensor working correctly by adding the dtoverlay to the boot/config.txt

I want to use a second sensor connected to a different GPIO pin

The following page https://pinout.xyz/pinout/1_wire   suggests this is possible atleast with raspberry PI.

dtoverlay w1-gpio gpiopin=4 pullup=0  # header pin 7
dtoverlay w1-gpio gpiopin=17 pullup=0 # header pin 11

This didn't work for me, neither sensor shows up after a reboot.  Probably some syntax or something silly
Anyone else succeeded?

**Comment by pintail120** [comment]
why does it not work on python3

**Comment by LightningShark25** [comment]
@pintail120   so you used the same GPIO pin 4 for both sensors?
I did all the other config you used - the difference was I was trying two different GPIO pins.
I'll try putting them on the same GPIO pin4 - thanks!

When it fails I get something similar in my octoprint log to @nfored  but I'm not on the upgraded python 3.
I suspect those messages appear when the sensors are not available??

**Comment by pintail120** [comment]
Yes same data pin for both.
The DS18B20 has a unique serial number, it uses its data pin like a bus, therefore only the correct DS18B20 will respond when addressed.
I have read somewhere that the DS18B20 will only work on gpio4, not sure how true that is but it was on one of the links I read.

This is my version of python:

**Comment by nfored** [comment]
I think only pin 4 is technically a 1 wire pin, much like only a single set of pins can do i2c.

**Comment by LightningShark25** [comment]
If you check the link I included in the original post you will see that onewire on other pins is possible.
I just didn't get it working properly
Either way if it works properly on GPIO 4 then its an easy fix.  Will report back when I get a chance..

**Comment by vitormhenrique** [comment]
using pin 4 is the way to go, with multiple on the same pin, only getting the serial number for each, have you tested it?

**Comment by pintail120** [comment]
yes, it works perfectly
two ds18b20 on pin 4
very happy

**Comment by LightningShark25** [comment]
Can confirm 2 sensors on PIN 4 working no issues.  Not quite what I was trying to do - but no fuss.
Thanks guys
