### ISSUE TITLE
Start/Stop Time Support

### ISSUE THREAD

**Issue by CWRRT** [vitormhenrique/OctoPrint-Enclosure#50]
Is it possible to add start/stop time support based on actual time. For example, I have my lights turn on at start of print but would like them to go off at 10pm.

Thank you and keep up the great work!

**Comment by vitormhenrique** [comment]
Definitely possible, I'll only have time to implement next month or so....

**Comment by vitormhenrique** [comment]
I just finished re-writing most of the plugin and **implemented this requested** feature, tested 95% of the plugin.

If you want to test it out uninstall the current plugin, go to the plugin manager, select get more, and where it says "from URL" use the development branch:

https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

More documentation here:
https://github.com/vitormhenrique/OctoPrint-Enclosure/tree/dev

I'll push this to production after more people test it out.

**Comment by CWRRT** [comment]
Just installed and will test out for a few days.

**Comment by CWRRT** [comment]
One thing I notice is that the auto turnoff only allows one or the other. In a perfect world, it would look like this.

Enclosure Lights
	Auto On during start of print
	Auto Off 60 seconds after print finishes OR turn off at 10pm, whichever comes first

**Comment by vitormhenrique** [comment]
When you start a print, you actually have a pretty good idea when it will finish, so you probably would know what time of schedule you would want. I'm against creating a new check box, and a new field on the plugin, the configuration is pretty big as it is.
Maybe creating a separate schedule output that you could add to different outputs would be a better solution to accomplish this. 
But I'll not do it now, I spent a lot of time to get this release done, and I need to work on other projects...

**Comment by vitormhenrique** [comment]
Implemented on V4.0
