### ISSUE TITLE
[Request] Navbar toggle button

### ISSUE THREAD

**Issue by leobel96** [vitormhenrique/OctoPrint-Enclosure#51]
Hi, It's me again, is it possible, in the next releases, to add toggle buttons for relay on the navbar (near the settings icon for example) like the "Octoprin PSU control" plugin? Maybe giving the possibility to choose which toggle add to the navbar and which not. Thank you!!

**Comment by vitormhenrique** [comment]
I just finished re-writing most of the plugin and **implemented this requested** feature, tested 95% of the plugin.

If you want to test it out uninstall the current plugin, go to the plugin manager, select get more, and where it says "from URL" use the development branch:

https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

More documentation here:
https://github.com/vitormhenrique/OctoPrint-Enclosure/tree/dev

I'll push this to production after more people test it out.

**Comment by leobel96** [comment]
Thank you!!! Now I uninstall it I install the devel one.

**Comment by leobel96** [comment]
@vitormhenrique I have installed it and it works fine, very good job!! Is it possible to add buttons on navbar as distinct buttons? I mean without having to click before on the cube

**Comment by vitormhenrique** [comment]
Because now it is possible to add too much information on the navbar, I opted for the sub-menu system. 

It’s a compromise between going to the enclosure tab and not having the ability at all.

Best regards,
Vitor Henrique

**Comment by leobel96** [comment]
Seems Logic. Time ago I opened anche issue about adding integration with telegram plugin. Are there news?

**Comment by vitormhenrique** [comment]
Implemented on V4.0
