### ISSUE TITLE
Gpio Output

### ISSUE THREAD

**Issue by marcoamr2002** [vitormhenrique/OctoPrint-Enclosure#60]
Hi,

I have an issue with the output function on my Orange Pi Zero.
I have configured the GPIO 5 for turn on/off the lighs with a relay. I can make the relay work with the gpio write 5 1 to turn on, and gpio write 5 0 to turn off in the command line but in the plugin nothin happens:
![captura de pantalla 2017-09-01 13 27 59](https://user-images.githubusercontent.com/27769671/29968034-1700cc16-8f1a-11e7-8c09-5738297805ee.png)
![captura de pantalla 2017-09-01 13 32 21](https://user-images.githubusercontent.com/27769671/29968036-19ff37ea-8f1a-11e7-9f11-031abc73c91a.png)
![captura de pantalla 2017-09-01 13 32 38](https://user-images.githubusercontent.com/27769671/29968037-1d0e7784-8f1a-11e7-9fb9-103aba546cb3.png)

What I´m doing wrong?

Sorry for my english

Marco

**Comment by vitormhenrique** [comment]
Simple: you are using a unsupported board. This plugin only works with Raspberry PI family. It rely on RPi.GPIO python library and utilize Raspberry Pi interrupts. 
I have no plans to port this plugin to other boards. Those could be major changes, and I don't have any orange pi board to test.
So you have 3 options:

1.  Use a raspberry pi
2.  Fork the plugin, make the necessary changes to work on orange pi, probably using this library: https://github.com/WereCatf/WiringOP
3.  Donate one orange pi so I can properly test and implement the changes
