### ISSUE TITLE
Momentary switch input

### ISSUE THREAD

**Issue by Allycat1972** [vitormhenrique/OctoPrint-Enclosure#61]
Hi. Great plugin! Just what a none programmer needs.  Can you please have another input option for momentary switch? I have a touch panel on my enclosure for local power and light control, however they are momentary and would need a toggle input for ON / OFF control. At the moment they work perfectly at switching on using the IO control, however I am unable to then switch them off. (or am I missing something?)

**Comment by Allycat1972** [comment]
Oh dear.  Just seen the toggle option....Sorry for wasting your time. Regards, Andrew

**Comment by vitormhenrique** [comment]
Glad to hear that you got it working. :)
