### ISSUE TITLE
Possibility to send custom gcode to printer

### ISSUE THREAD

**Issue by SirYwell** [vitormhenrique/OctoPrint-Enclosure#63]
I would like to be able to send custom gcode to my printer by pressing a button which is connected via GPIO. Examples: Set a temperature or moving the Z axis of the printer. Could you implement something like that?

**Comment by vitormhenrique** [comment]
That is a good idea, and it was already on the pipeline, it will be on the next release.

**Comment by vitormhenrique** [comment]
I just finished re-writing most of the plugin and **implemented this requested** feature, tested 95% of the plugin.

If you want to test it out uninstall the current plugin, go to the plugin manager, select get more, and where it says "from URL" use the development branch:

https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

More documentation here:
https://github.com/vitormhenrique/OctoPrint-Enclosure/tree/dev

I'll push this to production after more people test it out.

**Comment by vitormhenrique** [comment]
Implemented on V4.0
