### ISSUE TITLE
Toggle for Autostart

### ISSUE THREAD

**Issue by Tsalokin** [vitormhenrique/OctoPrint-Enclosure#65]
My printer is in my room and so I like it to shutoff when it's finishes at night, but I also sometimes print continuously which becomes a problem if I forget to turn off auto shutoff.
Toggling auto shut off is a little out of the way, it would be nice to have a toggle next to the buttons in the Enclosure Plugin tab. Maybe even an option to add or remove the button in settings, if it's not necessary for others.

**Comment by vitormhenrique** [comment]
but do you want a button on the plugin page that turns the printer off? or a button that changes the setting?
I need to do some research, i don't think it is possible to change the setting from other pages, it might, but I don't know how...

**Comment by vitormhenrique** [comment]
I just finished re-writing most of the plugin and **implemented this requested** feature, tested 95% of the plugin.

If you want to test it out uninstall the current plugin, go to the plugin manager, select get more, and where it says "from URL" use the development branch:

https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

More documentation here:
https://github.com/vitormhenrique/OctoPrint-Enclosure/tree/dev

I'll push this to production after more people test it out.

**Comment by vitormhenrique** [comment]
Implemented on V4.0
