### ISSUE TITLE
Outputs not working 

### ISSUE THREAD

**Issue by cpmorris** [vitormhenrique/OctoPrint-Enclosure#71]
Inputs are working fine and can trigger an output but the output  button and automatic start with print are not.  I also have psu plugin installed and it works correctly.

Thanks

**Comment by vitormhenrique** [comment]
I can not reproduce the issue, and the plugin is working for multiple people, I guess is some incompatibility with your setup or you are using incorrect gpio numbers.

Could you figure it out?

**Comment by vitormhenrique** [comment]
Can you please get back and say if you got it working?

**Comment by vitormhenrique** [comment]
I'm closing this issue due to the lack of response. I'll reopen if someone can give me a step-by-step instructions on how to reproduce it.
