### ISSUE TITLE
Change FIlament Script not working.

### ISSUE THREAD

**Issue by cpmorris** [vitormhenrique/OctoPrint-Enclosure#73]
Im not sure why but when the script is pushed its pushing as lowercase(even though its typed in caps in the plugin setup).  Terminal wont recognize some commands in lower case.

**Comment by cpmorris** [comment]
![pic 1](https://user-images.githubusercontent.com/32283466/32926522-53a40faa-cb0d-11e7-8b75-29d4ce930936.jpg)
![pic 2](https://user-images.githubusercontent.com/32283466/32926523-53d7ad10-cb0d-11e7-9e26-5374e23b7bd4.jpg)

**Comment by cpmorris** [comment]
Specifically the x y coordinates.  If I type them in caps directly in the terminal it works fine.  Thanks

**Comment by vitormhenrique** [comment]
you are right.

I just noticed that there is an issue on the code...

https://github.com/vitormhenrique/OctoPrint-Enclosure/blob/master/octoprint_enclosure/__init__.py#L436

I'll fix on the next release.

**Comment by vitormhenrique** [comment]
if you want to quick fix, just ssh to your rpi, find the line that I'm pointing and change it to upper instead of capitalize...

**Comment by cpmorris** [comment]
Any idea on timing?  I have some 60hr prints that exceed my spool quantity so this will be pretty handy. THanks

**Comment by cpmorris** [comment]
oh ok ill see if I can figure that out.

**Comment by cpmorris** [comment]
What and where is the file name to get the script?  I'm not familiar enough with the file structure on these yet but can get it swapped wonce I know where its at.

**Comment by vitormhenrique** [comment]
if you have a standard octopi installation, using the image pre-created for raspberry pi the file should be here:

/home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/

just edit the file __init__.py with the changes that I said, and restart your system.

**Comment by cpmorris** [comment]
One last question...what's the command for opening it in an editor?  Linux command line is foreign to me but I have located the file.

**Comment by vitormhenrique** [comment]
you need to open the file using a text editor, if you have zero experience editing files in linux search how to use nano.
it is not quite opening, using the mouse and changing the file.

**Comment by cpmorris** [comment]
yeah i had found nano but was having trouble oprining file....the file name has two underscores before and after

**Comment by cpmorris** [comment]
good to go thanks for the help!

**Comment by vitormhenrique** [comment]
fixed on https://github.com/vitormhenrique/OctoPrint-Enclosure/commit/bf6efc2cd1b7f06e09aa5b429f5fa0851ba19b77
