### ISSUE TITLE
Direct NeoPixel Support

### ISSUE THREAD

**Issue by dismaster** [vitormhenrique/OctoPrint-Enclosure#75]
As NeoPixel is directly supported via the PI would it be possible to add a choice if it's controlled through raspberry or arduino?

Please see attached python script with which you can control it directly - it required the Arduino library from here: http://frederickvandenbosch.be/?p=1014

thanks!
[neopixel.py.txt](https://github.com/vitormhenrique/OctoPrint-Enclosure/files/1500288/neopixel.py.txt)

**Comment by vitormhenrique** [comment]
I initially coded direct support, but, neopixel and raspberry pi, despite "work" is unreliable. 

I'll add as an option on next revision, but I discourage using it.

**Comment by dismaster** [comment]
Great stuff! Would be really great to get it!

**Comment by vitormhenrique** [comment]
I just finished re-writing most of the plugin and **implemented this requested** feature, tested 95% of the plugin.

If you want to test it out uninstall the current plugin, go to the plugin manager, select get more, and where it says "from URL" use the development branch:

https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip

More documentation here:
https://github.com/vitormhenrique/OctoPrint-Enclosure/tree/dev

I'll push this to production after more people test it out.

**Comment by vitormhenrique** [comment]
@comradequestion, you don't need to use your fork now, you can try installing the dev branch and check the other new features as well.

**Comment by vitormhenrique** [comment]
Implemented on V4.0

**Comment by RitchRock** [comment]
Is there anything else that needs to be installed for this to work?

Perhaps it's not supported on RasPi 3 B+.

**Comment by vitormhenrique** [comment]
Follow this guide:
https://learn.adafruit.com/neopixels-on-raspberry-pi?view=all

If it works
