### ISSUE TITLE
Show the target temperature

### ISSUE THREAD

**Issue by zoolanders49** [vitormhenrique/OctoPrint-Enclosure#79]
Hello,

I use your great plugin, I would like to propose some evolution. 
could you show somewhere the target temperature that is set. And show if the heater is running or not.

Thank you for your job

**Comment by vitormhenrique** [comment]
This is an issue with the new octoprint, it's a new bug, and will be fixed on the next version.

Unfortunately I have not had time to do any progress working on the plugin. Hopefully during the vacation I'll get back with new features and bug fixes.

It already has an issue opened, so I'm going to close this one.

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/68
