### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by ed12345678** [vitormhenrique/OctoPrint-Enclosure#86]
Would it be possible to add debounce timers to the inputs? mine will occasionally trip for no reason.

**Comment by vitormhenrique** [comment]
Inputs already have a 200ms bounce time. 

https://github.com/vitormhenrique/OctoPrint-Enclosure/blob/master/octoprint_enclosure/__init__.py#L429

Unusual trips might be an effect of power supply issues / wiring issues. You might want to add a capacitor on your button inputs and solve the issue.

Are you experiencing issues with filament sensors? Buttons? what...

**Comment by vitormhenrique** [comment]
Hi, are you still experiencing issues? have you tried my recommendations?

**Comment by vitormhenrique** [comment]
Closing as OP did not respond my questions.
