### ISSUE TITLE
Multiple Temperature Probes DHT22(on different GPIO Pins)

### ISSUE THREAD

**Issue by redangel1984** [vitormhenrique/OctoPrint-Enclosure#91]
Title says it all. I would like to be able to add two DHT22 sensor one for the enclosure itself and I have also a filament Spool-box where I need to check the Humidity now and then. Is it already possible to add two DHT22 sensors on different GPIOs?
Thank you

**Comment by vitormhenrique** [comment]
this is a duplicate from https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/59

I'm already adding to the next release.

**Comment by vitormhenrique** [comment]
I'm closing this issue, check issue https://github.com/vitormhenrique/OctoPrint-Enclosure/issues/59 for more information.
