### ISSUE TITLE
Compatibility of the project enclosure with MQ-2 + DHT-11 + relays + end of filament

### ISSUE THREAD

**Issue by didelamad** [vitormhenrique/OctoPrint-Enclosure#96]
![projet enclousre](https://user-images.githubusercontent.com/36919082/36783411-3317acfe-1c7c-11e8-9b9a-fa5985a23e47.jpg)

Can my project be compatible with your plugin?
The goal is to control the temperature of the cell by heating and extracting fan to pause the printer and to stop the heating with the filament sensor and finally in case of smoke detection to shut down the electrical circuit the printer, raspberry, cell temperature management and ringing the speaker

Est ce que mon projet peut être compatible avec votre plugin?
Le but est de contrôler la température de la cellule par le chauffage et le ventilateur d'extraction mettre en pause l'imprimante et d'arrêter la chauffe avec le capteur de filament et enfin en cas  de détection de fumée d'arrêter le circuit électrique de l'imprimante, du raspberry , de la gestion de la température de la cellule et de faire sonner le haut parleur

**Comment by vitormhenrique** [comment]
I'mm not really sure what you meant by "extracting fan to pause the printer and to stop the heating with the filament sensor"

- You can add fans and control them with the the plugin.
- You can add filament sensors and pause the printer when they are triggered.
- You can add smoke detectors to shutdown.

Everything is well documented, just install the plugin and play with it, also check other closed issues to figure it out if you have problems.
